### ISSUE TITLE
Extension does nothing.

### ISSUE THREAD

**Issue by desihack** [theahura/shoot-the-messenger#102]
i open messenger.com

while messages are open, i click on extension, and click deleted, i click continue on prompt. NOTHING happens.

**Comment by theahura** [comment]
Thanks for the bug report. Can you provide console logs, as described in the bug report template?

**Comment by desihack** [comment]
Im not sure how to do that. Can you guide me please.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by theahura** [comment]
going to merge this with #99 for now -- im working on a suite of fixes and will likely pick up whatever is going on with yours. In the meantime, you can get the console by hitting f12 or opening chrome settings

**Comment by desihack** [comment]
I have console open.

I have pressed f12

what should I do from here. Sorry for the lack of knowledge

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by theahura** [comment]
I think this issue should be fixed now so no need to give more logs. 
Just use the latest version on the chrome store
