### ISSUE TITLE
When i click "Remove Messages", nothing happens.

### ISSUE THREAD

**Issue by j0k34** [theahura/shoot-the-messenger#103]
**Describe the bug**
When i click on "Remove Messages" nothing happens.

**To Reproduce**
1. Go to https://www.messenger.com
2. Click on Remove messages
3. Nothing happens

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser - Chrome
 - Version 117.0.5938.89 (Official Build) (64-bit)

**Logs**
Add logs from the chrome dev console. Hit f12 and go to the console tab in the window that pops up, and attach what you see there as a txt file.
There is a lot of text in console but i copied only the "red" error one

main.js:83 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'scrollTop' in null            main.js:83
    at getScroller (main.js:83:24)
    at prepareDOMForRemoval (main.js:133:3)
    at unsendAllVisibleMessages (main.js:162:36)
    at runner (main.js:285:29)
    at removeHandler (main.js:393:24)

**Comment by theahura** [comment]
how many messages do you have in the chat? this error can occur if you have too few, resulting in no scroll bar being present

**Comment by theahura** [comment]
Should be fixed now
