### ISSUE TITLE
Won't click the Remove button

### ISSUE THREAD

**Issue by noahmoro** [theahura/shoot-the-messenger#105]
**Describe the bug**

I use the extension as instructed and it seems to work until it
has to click the blue Remove button. It goes from one message
to the next, attempting to click the remove button, but it doesn't. 
This continues until the last message or two, where it stops, thinks, 
and rinses and repeats. It goes back to going through the motions,
but never actually hitting remove. 

**To Reproduce**
1. Go to Messenger.com
2. Click on remove on the extension
3. let app run
4. See messages not being removed

**Expected behavior**
I am expecting that it would finish removing the message

**Screenshots**
I forgot to take screenshots sorry.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Home
 - OS Version: 10.0.22000 N/A Build 22000
 - Google chrome
 - Version 117.0.5938.89 (Official Build) (64-bit)

**Logs**
Add logs from the chrome dev console. Hit f12 and go to the console tab in the window that pops up, and attach what you see there as a txt file.
[Successfully added log to screen.txt](https://github.com/theahura/shoot-the-messenger/files/12656899/Successfully.added.log.to.screen.txt)

**Comment by noahmoro** [comment]
https://imgur.com/6nPeWc2

**Comment by theahura** [comment]
I left debug mode on :grimacing:

**Comment by theahura** [comment]
Should be fixed, lmk if its not

**Comment by noahmoro** [comment]
Thanks bro. do you like my profile pic be honest

**Comment by theahura** [comment]
its fine, my dogs are cuter

**Comment by noahmoro** [comment]
Its been workin pretty damn well so far gangsta, i notice it fails often but it isnt that big of a issue. i just have to press remove again and its starts back up. besides that everything is gangsta. thanks.

**Comment by theahura** [comment]
what happens when it fails? can you provide more details?

**Comment by noahmoro** [comment]
It just says there was an error when deleting messages, I have to press OK on the pop up, then i just start the process over.

**Comment by theahura** [comment]
is there anything in the log that looks like the error message? does it say what kind of error or anything?

**Comment by noahmoro** [comment]
It hasnt happened in the last 30 minutes or so next time it happens ill take a screen shot
