### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by ReedCent** [theahura/shoot-the-messenger#112]
**Describe the bug**
Whenever I press "Remove Messages", nothing happens.

**To Reproduce**
1. Go to the extension while at messenger.com
2. Click on 'Remove Messages'.
3. Nothing happens.

**Expected behavior**
For messages to start being unsended.

**Screenshots**
![Screenshot 2024-06-08 055039](https://github.com/theahura/shoot-the-messenger/assets/172093376/434bad28-90da-4542-97b6-df6814ef59fb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: Version 125.0.6422.142 (Official Build) (64-bit)

**Logs**
[www.messenger.com-1717815183284.txt](https://github.com/user-attachments/files/15746259/www.messenger.com-1717815183284.txt)

**Misc**
I've already tried to unsend one message as you can see at the very latest message and it seems to be possible to unsend for this chain.
Edit: I've also already tried to use the extension both from the Webstore and as a clone from here.

**Comment by theahura** [comment]
I wasn't able to replicate this :thinking: sometimes this sort of thing happens w/ facebook changing their algos, but in this case (on my end) it all looks the same. I'm a few versions of chrome behind though so i can maybe try that angle?

as it is otherwise, logs and stuff look fine. Which is actually even more surprising, _something_ usually breaks or throws an explicit error

**Comment by ReedCent** [comment]
> I'm a few versions of chrome behind though so i can maybe try that angle?

What version of Chrome are you on? Maybe I can try downgrading

**Comment by dollaruw** [comment]
I can confirm I am facing same issue after updating my browser to latest as I can see in updated browser messenger UI was changed recently.

**Comment by theahura** [comment]
Got it. Might be that. I'm on chrome 121, but I can try updating and seeing if that fixes it. Thanks a ton @dollaruw for the added information!

**Comment by ReedCent** [comment]
Okay so I've been looking around and I don't actually know how to downgrade Google Chrome and it seems I can't figure it out. The best lead I got was this which still didn't work with me: https://stackoverflow.com/questions/54927496/how-to-download-older-versions-of-chrome-from-a-google-official-site

How are things working on your end? Did updating Chrome manage to reproduce the issue?

**Comment by theahura** [comment]
Actually no, so I'm not sure it's a chrome version thing. This may be a messenger AB test that I'm just not part of yet, or it could be an OS thing (generally unlikely? but im on ubuntu so maybe?)

This makes it a bit hard for me to fix anything :cry: As of right now I can't easily figure out what UI elements actually changed --> i can't update the code to push the right buttons

**Comment by dollaruw** [comment]
I am on mac OS and on a older version of Brave browser which is based on Chromium v123. Now It unsent messages but misses few messages also sometimes unsent same message twice. Also sometime process got killed without removing all messages.

If you are not getting UI then you can try changing your browsers useragent to Mac OS browser and try.

**Comment by ReedCent** [comment]
So, after reinstalling Chrome, it finally worked. I also deactivated, reactivated and relogged in on my account but I doubt that affects anything.

However, similar to @dollaruw's case, it doesn't work optimally. Messages are either skipped without being unsent or unsent and then deleted from your end. Between the end of every message batch, there is a 50/50 chance wherein it either continues to the next batch flawlessly or it will misposition the selection and it'll target a message not in the right order, thus skipping some messages, or it'll target a message already unsent, thus unsending it twice. This can also affect the recipient's messages and accidentally removing their messages too.

Have not encountered process getting killed, though. Maybe it's because I haven't tested/waited long enough.

**Comment by theahura** [comment]
ok that weirdness i _was_ able to also experience, and can likely try and fix that

**Comment by theahura** [comment]
gonna merge this into #119
