### ISSUE TITLE
Error finding scroller

### ISSUE THREAD

**Issue by shanelecuyer** [theahura/shoot-the-messenger#114]
![image](https://github.com/theahura/shoot-the-messenger/assets/9566851/aec84253-70a3-4db8-95d5-3cd02e72ffae)
![image](https://github.com/theahura/shoot-the-messenger/assets/9566851/2d657ee4-0d82-487e-a4ff-8d55d3bafa0e)
![image](https://github.com/theahura/shoot-the-messenger/assets/9566851/156000d1-454f-41f5-a16a-abf1d641572e)

using up-to-date chrome. there are thousands of messages.

**Comment by theahura** [comment]
Ok so looks like the query selectors for the [PARTNER_CHAT_QUERY](https://github.com/theahura/shoot-the-messenger/blob/main/main.js#L13) and the [UNSENT_MESSAGE_QUERY](https://github.com/theahura/shoot-the-messenger/blob/main/main.js#L14) are out of date

This should be a pretty quick fix, will try and get this done by tomorrow

**Comment by SeanBannister** [comment]
For anyone else ending up here via google, I'm also experiencing this issue.

**Comment by theahura** [comment]
I did not get this done by tomorrow oops

**Comment by theahura** [comment]
ok should be fixed, deploying a new version to chrome store
