### ISSUE TITLE
Extensions not works

### ISSUE THREAD

**Issue by fanambynana** [theahura/shoot-the-messenger#115]
![unsend](https://github.com/theahura/shoot-the-messenger/assets/128455011/3df017a1-da3c-45c4-ae25-6644a01362ee)

**Comment by theahura** [comment]
thanks for taking the time to file this issue! Unfortunately the error message is basically as described -- you need to be using messenger.com. I recommend starting by opening messenger.com in your web browser, and then try and use StM
