### ISSUE TITLE
Not all messages are deleted

### ISSUE THREAD

**Issue by SeanBannister** [theahura/shoot-the-messenger#118]
I'm using the most recent version containing the pull request in #117 and noticed not all messages are deleted. It's rare but when deleting many 100's of messages you'll notice every now and then there'll be 1 or 2 remaining as you scroll back through the deleted messages. To clarify, these aren't messages that are undeletable which your extension mentions sometimes happens. I can manually remove these messages by hand or I can run the software again and it'll go back through and get them but this really slows down the process when trying to delete a lot of messages.

I also found a comment on the extensions chrome store listing where someone mentions the same issue.

**Comment by theahura** [comment]
merging this into #119
