### ISSUE TITLE
 ERROR: something went wrong. Failed to complete removal  + not all messages are deleted -> Any tips to overcome those issues ?

### ISSUE THREAD

**Issue by Eminmpenza** [theahura/shoot-the-messenger#119]
**Describe the bug**

Hi,
Firstly, I would like to say that I'm very grateful about this script and I would like to thank his creator for his amazing job. It really helps and saves me a lot of time !
The "bugs" that I'm talking about here have already been discussed in some others reports. 

The main problem is the script will eventually stop at some point and the following message will appear : 

**ERROR: something went wrong. Failed to complete removal**  

I have to relaunch the script any time it does this, and it will work fine until the same message shows again. I am currently deleting a long conversation that includes many years of chat, and I can't really launch the script and do something else because I have to be around and be ready to relaunch it when necessary.

The second problem is that the script won't always delete all messages, and it can skip a few (sometimes more than a few) in a row. It also makes me relaunch the script several times where it has already been running to unsend the remaining skipped messages. I can also delete those skipped messages manually.

**To Reproduce**
1. Go to : https://www.messenger.com/ and select a conversation chain
2. Click on the "shoot-the-messenger" extension and then on "Remove Messages"
3. Let the script run for a while
4. The script stops and a small window displays "ERROR: something went wrong. Failed to complete removal"
5. Check for messages that have been skipped (not unsent) by the script
5. Start to run the script again from where it stopped and/or where it left some messages not unsent

**Expected behavior**
The script runs and unsends all the messages without interruption until none of the messages remain. In others words, the user has to start the script **one time and only one time** (for a given conversation chain) and can let it run until full unsending of all messages has been completed. No other runs are necessary to handle a given conversation chain. The script won't skip any messages to unsend.

**Screenshots**
![image](https://github.com/user-attachments/assets/8a198f5e-afd4-424d-9e4f-41be560e66d8)
![image](https://github.com/user-attachments/assets/cf9cf34f-93cc-4014-af09-f3ce6986d73d)

**Desktop (please complete the following information):**
 - OS : Windows 11
 - Browser : Opera, Chrome, Edge, Vivaldi and Arc. I have tried the script on all of those browsers and the problems remains in all fo them althought it seems to work best on Chrome and Opera (the script will run for longer without stopping on those two browsers)
 - Version : Version 6.1.0 both Chrome Web Store and developer version. The problems remains on the two versions.

**Logs**
[shoot-the-messenger-bug.txt](https://github.com/user-attachments/files/16677231/shoot-the-messenger-bug.txt)

____________________________________________________________________________________________________________________________________

I know it has already been discussed, but I am not able to find any solutions to those two problems. 
Does anyone have tips or advice to improve the script efficiency or at least diminish at most the interruptions and/or the skipped messages ?

I would gladly appreciate it !

Thanks in advance.

**Comment by theahura** [comment]
im recently funemployed so I have some more time to support this! will try and see whats going on today

**Comment by theahura** [comment]
ok so wrt skipping messages, that's a tough bug to replicate. I sent myself something like 200 test messages and in that list, it skipped over one of them. First I was like, 'o that's a problem'. But then the system fixed itself on the next cycle, without any manual intervention. Are you _sure_ that shoot the messenger does not eventually circle back to the messages that you think are being skipped over?

**Comment by theahura** [comment]
WRT the 'something went wrong' message, can you send over additional logs? Those are located on the bottom right of the screen and it should help indicate why it failed

**Comment by theahura** [comment]
ok getting closer to a few culprits
- seems like the search feature isnt working (this thing always breaks tbh) which might be causing the 'something went wrong' errors
- independently it looks like sometimes the system highlights messages from _other_ people accidentally, which causes problems because it thinks its deleting your message but it doesn't actually do so

**Comment by Eminmpenza** [comment]
> Are you sure that shoot the messenger does not eventually circle back to delete the messages that you think are being skipped over?

No, the skipped messages stay that way and the script never goes back on its own to remove them. If I want those skipped messages removed, I have to run the script again back from where the messages were left unremoved.


> ok getting closer to a few culprits
> 
>     * seems like the search feature isnt working (this thing always breaks tbh) which might be causing the 'something went wrong' errors
> 
>     * independently it looks like sometimes the system highlights messages from _other_ people accidentally, which causes problems because it thinks its deleting your message but it doesn't actually do so

Yes, you nailed it.
It's exactly what it does.

> 
> WRT the 'something went wrong' message, can you send over additional logs? Those are located on the bottom right of the > screen and it should help indicate why it failed

The conversation I have been deleting is almost fully removed from my messages.

I'll try to run the script on another one, and I'll keep you updated with the new logs it generates.

Thanks for your answer and your work !

**Comment by theahura** [comment]
ok I just pushed a bunch of fixes that I think should solve both of these issues. LMK if this is still causing problems on your end

**Comment by Eminmpenza** [comment]
Thanks !

I have tested the new version which seems to work fine for a while until a new kind of error pop up.

![image](https://github.com/user-attachments/assets/98f4e58c-6e7a-4075-92d7-1e10574103da)

The page now shows "couldn't load chats" error message.

I'm gonna try to run it again a few times to come with logs information about what goes wrong.

**Comment by Eminmpenza** [comment]
> Thanks !
> 
> I have tested the new version which seems to work fine for a while until a new kind of error pop up.
> 
> ![image](https://private-user-images.githubusercontent.com/176836852/364720592-98f4e58c-6e7a-4075-92d7-1e10574103da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzA0MzQsIm5iZiI6MTcyNTUzMDEzNCwicGF0aCI6Ii8xNzY4MzY4NTIvMzY0NzIwNTkyLTk4ZjRlNThjLTZlN2EtNDA3NS05MmQ3LTFlMTA1NzQxMDNkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwOTU1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzZmMTkyNjEzMGUyYWI2YmM4MjQ1ZjUyMDM1OTRmNjIyNDkzNGQ1YWQzODJmYjNlNjdjMDcyNDM5ZWUwNTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s6CUU2BXNvWnuPo2QzU_9l8KXdJWCnGt5FdI_6ZQRcA)
> 
> The page now shows "couldn't load chats" error message.
> I'm gonna try to run it again a few times to come with logs information about what goes wrong.

![image](https://github.com/user-attachments/assets/aac95378-9a05-4bad-a99f-69dffca957f1)


Log related to the new error.

It seems to always crash just after the script points one of my already unsent messages, as it would like to remove it, but instead, the script would try to prevent to remove it (where it was sometimes removing my already unsent messages before your last fix) and this seems to cause the error.

Let me know if you need more informations about the logs and feel free to let me know how to properly report them here because I am not a developper and I may not give your the right informations as you would expect them.

**Comment by theahura** [comment]
O yea that's because the script is trying to hide all the 'you unsent a message' rows and there are too many that fb gets tripped up :thinking: let me take a look again

**Comment by theahura** [comment]
Just pushed a new update, check that out. Also includes a 'delete all' mode

**Comment by Eminmpenza** [comment]
Hi, thanks for your update.

Seems like it's still glitching after a while. I run the default mode, and it was working fine until it wasn't anymore.
I recorded to show you what happen.

https://github.com/user-attachments/assets/fc7e1342-dfbd-4a8a-9e15-3ff4ef23344f

![image](https://github.com/user-attachments/assets/56dca0c0-056e-431c-9dcc-f416815fc8b1)

**Comment by theahura** [comment]
huh! that's pretty weird! no idea why it's doing that, will have to dig into it. Those logs also seem pretty...empty? there should be more there :thinking:

**Comment by Eminmpenza** [comment]
I run it again until it did the same bug.

Are you able to see what's going on with this one ?

![image](https://github.com/user-attachments/assets/86be7755-86a0-4629-a77b-1f0dcb8152b5)

**Comment by gaveitatry2** [comment]
I never saw such a broken, worthless, piece of garbage in my life. It didn't work September 2023. And it still doesn't work a year later. But this developer still acts like everything is peachy. It only took a year for him to add the "Delete All" feature that I suggested, and it doesn't even work right. It's deleting the other person's comments, but not mine. And it doesn't even start on the latest message. It starts at some random message months previous to the latest message. And after a few seconds, it stops working completely and throws an error message. I tried being polite and nice before, but this developer is an arse. So I'm just going to say it like it is. It's a piece of garbage but he won't admit that it won't work. He will keep wasting everyone's times. He will keep begging for free coffee donations and will take your money.

**Comment by bluevex** [comment]
I'm getting this error, latest chrome latest version on chrome store - the script fails in two ways for me. The first is this one, the "ERROR: something went wrong. Failed to complete removal." after clicking the dialogue, "Completed runner iteration but did not finish removal. Could not find searchable message..." is printed. The second failure mode is when it identifies and searches a string, but facebook does not return the result it should in the search window. I can solve this one by re-searching or randomly removing words in the search string until facebook properly performs the search. Let me know if I can provide more logs or screenshots for these failure modes somehow...

**Comment by theahura** [comment]
Hmm ok I'll take another look tomorrow. The issue is that it's pretty hard to fix without being able to replicate. Maybe I need to try on windows instead of Ubuntu 🤔

**Comment by theahura** [comment]
ok i think i might just get rid of the search feature entirely. It's way too buggy, breaks constantly, and it's hard to communicate to users what's going on anyway. So i'm just going to get rid of that part of the tool. 

It's a bit of a bummer, because I think it makes this tool much less useful :shrug:

**Comment by theahura** [comment]
Alright latest version removes everything related to search, and all messages are deleted from both sides now
