### ISSUE TITLE
Not working on my browser, buttons does nothing

### ISSUE THREAD

**Issue by Arcasar** [theahura/shoot-the-messenger#12]
Hi! Thank you for your work on this, I have been looking for something similar for a long while. :D

Perhaps I am not using it correctly : I download the extension and installed it via ''load unpacked'' on chrome. When I click on it while on facebook/messenger, i see the box with ''remove messages, scroll down inbox, stop removal''. When I click on remove messages, a confirmation box appears, yet when I click ok nothing happens. Nothing gets deletes. The 2 other buttons are unresponsive

Did I install this correcly? Sorry if it's a stupid question, i have never installed an extension manually.

Here is the error i get when trying the ''remove message'' button

Error handling response: TypeError: Cannot read property 'id' of undefined
    at chrome-extension://dmacgfehpiekkfehfoaaapakmehblcdb/background.js:28:41

**Comment by theahura** [comment]
O that's really interesting. Didn't expect an error in background.js. 

Ok so roughly that line is here:
```
if (request.action === "REMOVE") {
      // Begin removing message information.
      chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
        chrome.tabs.sendMessage(tabs[0].id, { tabId: tabs[0].id, ...request });
      });
```

looks like it's saying that the chrome tabs aren't being loaded, like tabs[0] isn't actually displaying anything. Can you make sure the file called manifest.json has 'activeTab' and 'tabs' under 'permissions'? 

Also, if you could screencap or textdump the full dev console logs (in messenger, hit f12 and go to the tab called console). Finally, if you go to chrome://extensions, you should see the box for Shoot the Messenger. There will be a link for 'background page'. Send me a screencap or textdump of that too.

**Comment by Arcasar** [comment]
![image](https://user-images.githubusercontent.com/40801244/110669120-4ec86700-81cc-11eb-99c8-bdeb440f47bf.png)

Thanks for the quick replay. Here's what I get

**Comment by Arcasar** [comment]
![image](https://user-images.githubusercontent.com/40801244/110669308-7d464200-81cc-11eb-9d8f-477b53d148b9.png)

**Comment by Arcasar** [comment]
![image](https://user-images.githubusercontent.com/40801244/110669578-c1d1dd80-81cc-11eb-9ebf-fe067a8984a2.png)
**

**Comment by theahura** [comment]
manifest looks fine. 

The f12 console I'm going to have to ask you to send again if possible, and can you send the text dump instead of the screencap? Those errors are from facebook, and aren't useful. 

Also, I meant the background page link located here:
![image](https://user-images.githubusercontent.com/6380637/110670529-7a7f2900-819b-11eb-8aba-edcc2551f6bc.png)

which should be at the url chrome://extensions

**Comment by Arcasar** [comment]
Hi! Sorry about that, I had problems copying the text dump. 

(function () {
  chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (!("action" in request)) {
      console.log("No action found in contentHandler.");
      return;
    }
    console.log("Got request: ", request);

    if (request.action === "STORE") {
      // Store in local storage.
      console.log("Got store request for: ", request.data);
      chrome.storage.local.set(request.data, () => {
        if (request.response) {
          chrome.tabs.sendMessage(sender.tab.id, request.response);
        }
      });
    } else if (request.action === "DELETE") {
      // Remove from localstorage.
      console.log("Got delete request for: ", request.data);
      chrome.storage.local.remove(request.data, () => {
        if (request.response) {
          chrome.tabs.sendMessage(sender.tab.id, request.response);
        }
      });
    } else if (request.action === "REMOVE") {
      // Begin removing message information.
      chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
        chrome.tabs.sendMessage(tabs[0].id, { tabId: tabs[0].id, ...request });
      });
    } else if (request.action === "SCROLL") {
      chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
        chrome.tabs.sendMessage(tabs[0].id, { tabId: tabs[0].id, ...request });
      });
    } else if (request.action === "STOP") {
      // Clear the storage cache and then trigger a reload. By clearing the
      // cache first, we make sure we do not trigger additional removal on this
      // page without confirmation.
      chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
        chrome.storage.local.set({ [tabs[0].url]: {} }, () => {
          chrome.tabs.sendMessage(tabs[0].id, {
            tabId: tabs[0].id,
            action: "RELOAD",
          });
        });
      });
    } else if (request.action === "CHECK_ALREADY_REMOVING") {
      if (sender.tab && sender.tab.active) {
        // If we have a refresh on a tab that we're currently removing data from,
        // restart the data removal. Otherwise, check local storage to see if we
        // have previously stored info there.
        chrome.storage.local.get([sender.tab.url], (result) => {
          if (!result || Object.keys(result).length === 0) return;
          console.log("Found storage for url: ", result);
          if ("isRemoving" in result[sender.tab.url]) {
            chrome.tabs.sendMessage(sender.tab.id, {
              tabId: sender.tab.id,
              action: "REMOVE",
            });
          } else if ("confirmSuccess" in result[sender.tab.url]) {
            chrome.tabs.sendMessage(sender.tab.id, {
              tabId: sender.tab.id,
              action: "CONFIRM_SUCCESS",
            });
          }
        });
      }
    } else {
      console.log("Unknown action requested: ", request.action);
    }
  });

  chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {});
})();

On the lower console I get this

background.js:7 Got request:  {action: "REMOVE"}
background.js:7 Got request:  {action: "REMOVE"}
background.js:7 Got request:  {action: "REMOVE"}
background.js:7 Got request:  {action: "REMOVE"}
background.js:7 Got request:  {action: "REMOVE"}
background.js:7 Got request:  {action: "REMOVE"}

So this is what I get, it add a line everytime I press the button and no errors are present.

**Comment by theahura** [comment]
Ok we're almost there. It looks like background.js is working fine, so not sure why the original post you had was failing

(this one: 
```Error handling response: TypeError: Cannot read property 'id' of undefined
at chrome-extension://dmacgfehpiekkfehfoaaapakmehblcdb/background.js:28:41```)

So can you try to run it one more time, hit f12 to open the devtools, go to the console tab, and text dump all of that?

**Comment by Arcasar** [comment]
static.xx.fbcdn.net/rsrc.php/v3/yd/r/LpT7unRLP6o.js?_nc_x=j1HlYS1YE3f:59 ErrorUtils caught an error:

epoch mismatch

Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs.
b @ static.xx.fbcdn.net/rsrc.php/v3/yd/r/LpT7unRLP6o.js?_nc_x=j1HlYS1YE3f:59

**Comment by Arcasar** [comment]
Wow haha. Never used the messenger site before. Thank you so much for you patience!

**Comment by theahura** [comment]
No worries, gonna close this assuming it's all good.
