### ISSUE TITLE
Making the script working both on messenger.com and facebook.com/messages/t

### ISSUE THREAD

**Issue by Eminmpenza** [theahura/shoot-the-messenger#120]
Hi,

Could it be possible to make this awesome script also working on facebook.com/messages/t ?

I rather use this way and URL because I find it way less slow and bloated than messenger.com (like a messenger lite on desktop) when it comes to browsing messages.

Maybe it could speed up the process or allow it to be smoother.

**Comment by theahura** [comment]
unfortunately I don't think I want to support two separate URLs. That would pretty significantly increase the bug surface area, because this thing breaks any time theres an update to fb's ui. Thanks for the suggestion though!
