### ISSUE TITLE
Option to unsend my messages only and not remove the other party's messaages

### ISSUE THREAD

**Issue by Sword1611** [theahura/shoot-the-messenger#123]
**Describe the feature you'd like**

This script is very cool, however I find it slow because of removing messages will also remove the messages of the other person.
I do not need to delete their messages I mean if that is the case I can just delete the whole conversation for that sake right? But I found this cool script that will unsend messages, so if you would please make a setting or an option to only unsend my messages and not the other party that would be great. And if that setting is already there but I'm just dumb to see it, please let me know!

**Comment by theahura** [comment]
I really want to be able to support this, and for a long long time the extension would work like this by default, but in the most recent release I decided to remove this feature and I won't be bringing it back.

The main reason is that supporting this feature is buggy af. It requires all sorts of complicated logic to search through messages, which would break often. There's a bunch of other issues about this subject, the most recent (where I got rid of the search ability and as a result the ability to just remove your messages) is here: https://github.com/theahura/shoot-the-messenger/issues/119
