### ISSUE TITLE
Pop up box is half way off the screen

### ISSUE THREAD

**Issue by Trixing16** [theahura/shoot-the-messenger#13]
When I click delete all messages the pop up box appears halfway off the screen and I am unable to select continue

**Comment by Arcasar** [comment]
Hi! I have this issue too. you can enter press enter to confirm or click it in windowed chrome.

**Comment by theahura** [comment]
Wait this is really weird. I don't know if this would be anything to do with this extension, but can you send a screenshot?

**Comment by theahura** [comment]
No updates in a while, so closing this.
