### ISSUE TITLE
Thumbs-up and link-dense chats have trouble with removing messages

### ISSUE THREAD

**Issue by Avamander** [theahura/shoot-the-messenger#14]
It would be really nice if the plugin tried to create a list of messages it failed to remove and skip those if possible.

It seems to get stuck if all the messages that initially load are links because those can't be removed.

**Comment by theahura** [comment]
I think it _does_ do this already. See here: https://github.com/theahura/shoot-the-messenger/blob/main/main.js#L99 it removes stickers and links. Not sure about thumbs up, those may not be counted but I can add code for that if needed. 

Can you confirm that you have the latest version and that links are still getting flagged?

**Comment by Avamander** [comment]
> Not sure about thumbs up, those may not be counted but I can add code for that if needed.

Some thumbs up are removable, some are not. Not sure why.

I have the latest release.

**Comment by Avamander** [comment]
I should mention that ideally it wouldn't want to remove links or stickers just for myself, instead at some point FB fixes their removal and I can unsend them.

**Comment by theahura** [comment]
So this thing is a bit fault tolerant. The way it works is, it will try to remove stuff and if it can't after a while it will skip it and get to it on the next refresh. Probably that's what is happening with the thumbs-ups. If you've run this for a while and you still see thumbs-ups near the bottom, reopen this issue.

And yea, as of now links and stickers are just broken on facebook's end. You can try and remove them manually, I'm not sure that will work either though. I'd actually be curious so if you do try that let me know

**Comment by Avamander** [comment]
> You can try and remove them manually, I'm not sure that will work either though. I'd actually be curious so if you do try that let me know

Nope doesn't work. I've also seen a few received links that can't be deleted.

@theahura 

> If you've run this for a while and you still see thumbs-ups near the bottom, reopen this issue.
> The way it works is, it will try to remove stuff and if it can't after a while it will skip it and get to it on the next refresh.

I have let it work, but it does error quite a bit, some likes remain at the bottom (amongst the links). I suspect the amount it has to skip is so large by now that it takes a long time after a refresh to unsend a few real messages.

**Comment by Avamander** [comment]
@theahura 

I've watched it for a few days now and now it totally fails to remove messages, it doesn't even scroll up enough to load messages it could delete.

**Comment by theahura** [comment]
Ok cool, thanks a ton for keeping up on this. I'll reopen it and add a fix for removing thumbs.

**Comment by theahura** [comment]
Sorry about taking so long with this, but I finally got around to it. Thumbs should be handled now.
