### ISSUE TITLE
add new freature to delete only from my side.

### ISSUE THREAD

**Issue by jahid01711** [theahura/shoot-the-messenger#15]
**so i have used this for 4 times. and in liked it but there is a problem and that is that it removes the messages that I **got** and also the message that i send so it doesn't make any sense .so i want you to add an option to only delete messages that i send not the messages i got.**

**Comment by jahid01711** [comment]
hope to hear from you soon.

**Comment by theahura** [comment]
Can't do it. TLDR: back up your data if you want it.

Long version: 

Very roughly speaking, there's a memory problem. When you scroll up enough, Chrome runs out of memory and the entire browser crashes. If you have chains that go back even months, you'll run into this issue. To get around this, we need to be able to refresh the page and still somehow have a way of going back to the place where we left off. Originally, I could do this with the search in conversation feature; however, this no longer works programatically. So the only alternative is to just delete everything. 

If there is a way to use the search bar, or some other thing, I'd be able to do it. But as of right now I don't think it's possible.
