### ISSUE TITLE
The script isn't unsending

### ISSUE THREAD

**Issue by NibbaMakesDespacito2** [theahura/shoot-the-messenger#16]
The script can move conversations all the way to the beginning and and scroll my chat to the beginning too, but when I press "remove messages" it does nothing at all. Please help?

**Comment by theahura** [comment]
Thanks for opening an issue. I'm gonna need some more info. 

Can you grab a text dump of the console logs (hit f12 to open developer tools and then go to console). And can you do the same for the console logs of the background task (go to chrome://extensions and hit background page for Shoot the Messenger).

Can you also dump the html of the page you're trying to remove?

**Comment by NibbaMakesDespacito2** [comment]
Oh gosh, I'm not that tech savvy, but I'll try I guess. Just copy and paste the text from console here? Or maybe a screenshot would help more?

**Comment by NibbaMakesDespacito2** [comment]
Checking existing removal process.
main.js:439 Got action:  REMOVE
main.js:388 On run:  0
main.js:234 Starting runner removal for N iterations:  5
main.js:236 Running count: 0
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at longChain (main.js:389)
    at removeHandler (main.js:416)
    at main.js:442
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []
main.js:217 No scroller or load buttons, but we didnt hit the top. Failing.
main.js:236 Running count: 1
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at async longChain (main.js:389)
    at async removeHandler (main.js:416)
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []
main.js:217 No scroller or load buttons, but we didnt hit the top. Failing.
main.js:236 Running count: 2
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at async longChain (main.js:389)
    at async removeHandler (main.js:416)
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []
main.js:217 No scroller or load buttons, but we didnt hit the top. Failing.
main.js:236 Running count: 3
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at async longChain (main.js:389)
    at async removeHandler (main.js:416)
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []
main.js:217 No scroller or load buttons, but we didnt hit the top. Failing.
main.js:236 Running count: 4
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at async longChain (main.js:389)
    at async removeHandler (main.js:416)
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []
main.js:244 Completed run.
main.js:390 Runner status:  continue
main.js:388 On run:  1
main.js:234 Starting runner removal for N iterations:  5
main.js:236 Running count: 0
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at longChain (main.js:389)
    at async removeHandler (main.js:416)
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []
main.js:217 No scroller or load buttons, but we didnt hit the top. Failing.
main.js:236 Running count: 1
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at async longChain (main.js:389)
    at async removeHandler (main.js:416)
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []
main.js:217 No scroller or load buttons, but we didnt hit the top. Failing.
main.js:236 Running count: 2
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at async longChain (main.js:389)
    at async removeHandler (main.js:416)
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []
main.js:217 No scroller or load buttons, but we didnt hit the top. Failing.
main.js:236 Running count: 3
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at async longChain (main.js:389)
    at async removeHandler (main.js:416)
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []
main.js:217 No scroller or load buttons, but we didnt hit the top. Failing.
main.js:236 Running count: 4
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at async longChain (main.js:389)
    at async removeHandler (main.js:416)
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []
main.js:244 Completed run.
main.js:390 Runner status:  continue
main.js:388 On run:  2
main.js:234 Starting runner removal for N iterations:  5
main.js:236 Running count: 0
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at longChain (main.js:389)
    at async removeHandler (main.js:416)
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []
main.js:217 No scroller or load buttons, but we didnt hit the top. Failing.
main.js:236 Running count: 1
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at async longChain (main.js:389)
    at async removeHandler (main.js:416)
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []
main.js:217 No scroller or load buttons, but we didnt hit the top. Failing.
main.js:236 Running count: 2
main.js:103 Removing bad rows from dom:  (2) [div.oajrlxb2.gs1a9yip.tdjehn4e.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]
2main.js:110 TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:237)
    at async longChain (main.js:389)
    at async removeHandler (main.js:416)
main.js:124 Found hidden menu holders:  NodeList []
main.js:136 Clicking more buttons:  []




This is from the console.

**Comment by theahura** [comment]
Cool, this is helpful already. 

`main.js:124 Found hidden menu holders: NodeList []`

means that it's unable to find the button that we need to press to actually remove the message. The HTML dump would be really helpful here. The way you get that is, hit f12 to open the dev console and then go to elements. Then, follow the instructions here:

https://stackoverflow.com/questions/23343191/copying-html-code-in-google-chromes-inspect-element

If you could upload that as a file, I'd appreciate it.

**Comment by NibbaMakesDespacito2** [comment]
The console logs from the extension are empty, don't show any text at all. Also, the page I'm trying to clear is just a normal messenger.com chat I had with a friend, like 4 or 5 messages.

**Comment by NibbaMakesDespacito2** [comment]
Wait my bad, the console logs actually showed this:

background.js:7 Got request:  {action: "REMOVE"}
background.js:7 Got request:  {action: "REMOVE"}
background.js:7 Got request:  {action: "CHECK_ALREADY_REMOVING"}
background.js:53 Found storage for url:  {https://www.messenger.com/t/100000802962642: {…}}
background.js:7 Got request:  {action: "REMOVE"}
background.js:7 Got request:  {action: "STORE", data: {…}, response: {…}}
background.js:11 Got store request for:  {https://www.messenger.com/t/100000802962642: {…}}
background.js:7 Got request:  {action: "CHECK_ALREADY_REMOVING"}
background.js:53 Found storage for url:  {https://www.messenger.com/t/100000802962642: {…}}
background.js:7 Got request:  {action: "STOP"}
background.js:7 Got request:  {action: "CHECK_ALREADY_REMOVING"}
background.js:53 Found storage for url:

**Comment by theahura** [comment]
> The console logs from the extension are empty, don't show any text at all. Also, the page I'm trying to clear is just a normal messenger.com chat I had with a friend, like 4 or 5 messages.

So messenger will often run a/b tests that will totally break the extension. Trying to see if that's the cause.

**Comment by NibbaMakesDespacito2** [comment]
> Cool, this is helpful already.
> 
> `main.js:124 Found hidden menu holders: NodeList []`
> 
> means that it's unable to find the button that we need to press to actually remove the message. The HTML dump would be really helpful here. The way you get that is, hit f12 to open the dev console and then go to elements. Then, follow the instructions here:
> 
> https://stackoverflow.com/questions/23343191/copying-html-code-in-google-chromes-inspect-element
> 
> If you could upload that as a file, I'd appreciate it.

I'll do it right now, give me a few minutes.

**Comment by NibbaMakesDespacito2** [comment]
[edit html.txt](https://github.com/theahura/shoot-the-messenger/files/6199826/edit.html.txt)
[unedited html.txt](https://github.com/theahura/shoot-the-messenger/files/6199831/unedited.html.txt)

Here goes nothing.

**Comment by theahura** [comment]
Cool, thanks a ton. I recommend deleting the files above, just for security reasons. I'll get back to you in a bit, but one thing to try is to see if you need to switch language settings to english somewhere

**Comment by theahura** [comment]
Yep, that's the issue. 

In the html of your messenger, you have a div with the following label:

```
<div aria-expanded="false" aria-haspopup="menu" aria-label="AÃ§Ãµes de mensagem" class="oajrlxb2 gs1a9yip g5ia77u1 mtkw9kbi tlpljxtp qensuy8j ppp5ayq2 goun2846 ccm00jje s44p3ltw mk2mc5f4 rt8b4zig n8ej3o3l agehan2d sk4xxmp2 rq0escxv nhd2j8a9 j83agx80 mg4g778l btwxx1t3 pfnyh3mw p7hjln8o kvgmc6g5 cxmmr5t8 oygrvhab hcukyx3x tgvbjcpo hpfvmrgz jb3vyjys rz4wbd8a qt6c0cv9 a8nywdso l9j0dhe7 i1ao9s8h esuyzwwr f1sip0of du4w35lb lzcic4wl abiwlrkh p8dawk7l mkd47r93 rgmg9uty" role="button" tabindex="-1"><div class="n00je7tq arfg74bv qs9ysxi8 k77z8yql i09qtzwb n7fi1qx3 b5wmifdl hzruof5a pmk7jnqg j9ispegn kr520xx4 c5ndavph art1omkt ot9fgl3s" data-visualcompletion="ignore"></div></div>
```

Note this line:

`aria-label="AÃ§Ãµes de mensagem" `

That's an issue. In our code, we look for the following: 

`MORE_BUTTONS_HOLDER_QUERY = '[aria-label="Message actions"]';`

Can you try setting your language to English and report back?

**Comment by jtagcat** [comment]
jfyi you are leaking metadata with the messenger.com/t/01189998 links

**Comment by theahura** [comment]
Right, thanks for catching that. @NibbaMakesDespacito2 please delete the logs you posted above. Got what we needed to identify the issue. In the future I'll recommend folks email me or something.

**Comment by NibbaMakesDespacito2** [comment]
Welp my bad, nothing too important though, but thank you guys, gonna change the language to English (US) first and if it doesn't work to English (UK). Just a few minutes.

**Comment by NibbaMakesDespacito2** [comment]
And of course you're right, the problem was the language overall, thank you so much for the help. If in the future you want to implement something in the code so it works in other languages, maybe I can help with checking out the the different words?Again, thank you so much.

**Comment by theahura** [comment]
Would love the help! I have no plans for implementing that right now, but the code is relatively straightforward (I think) so shouldnt be too hard to implement (or fork)
