### ISSUE TITLE
Not unsending in English language Chrome 89.0.4389.114

### ISSUE THREAD

**Issue by etheaven** [theahura/shoot-the-messenger#17]
Hello I'm using newest Chrome at current time when I'm writing this: "Version 89.0.4389.114 (Official Build) (64-bit)"  
Disabled all extensions, allowed Allow in incognito for this extension, tested both inside/outside incognito.  
  
Example of my HTML:  
`<a aria-label="New Message" class="oajrlxb2 tdjehn4e qu0x051f esr5mh6w e9989ue4 r7d6kgcz rq0escxv nhd2j8a9 j83agx80 p7hjln8o kvgmc6g5 cxmmr5t8 oygrvhab hcukyx3x jb3vyjys rz4wbd8a qt6c0cv9 a8nywdso i1ao9s8h esuyzwwr f1sip0of lzcic4wl l9j0dhe7 abiwlrkh p8dawk7l bp9cbjyn s45kfl79 emlxlaya bkmhp75w spb7xbtv rt8b4zig n8ej3o3l agehan2d sk4xxmp2 taijpn5t tv7at329 thwo4zme" href="/messages/new/" role="link" tabindex="0"><i class="hu5pjgll lzf7d6o1 sp_YitFLBd7Z7T sx_c9f27f"></i><div class="s45kfl79 emlxlaya bkmhp75w spb7xbtv i09qtzwb n7fi1qx3 b5wmifdl hzruof5a pmk7jnqg j9ispegn kr520xx4 c5ndavph art1omkt ot9fgl3s" data-visualcompletion="ignore"></div></a>`

The Console says nothing from the extension side, however these are in:  

```
7N6EYpH9jlW.js?_nc_x=O8pUiO1ZpOC:54 ErrorUtils caught an error:

Blocked a frame with origin "https://www.facebook.com" from accessing a cross-origin frame.

Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs.
errorListener @ 7N6EYpH9jlW.js?_nc_x=O8pUiO1ZpOC:54
4Zvbl3kzLe2vCsqT4Yp0DUqhCR7p9V8W-hH0ansD3jSLacDPUgWq3K0dw7kKDrPxyB321svkY5Nq25jlDq5g0X89Tv9bXKu_GbAxeWoyEaUZwQnVryFadZo0DqR2bHPFkrlT391tEDRB_IDmH8CsAaZNVNFzF0OkcxgBp4ptOr7_aKpw8BQAR8WMpWGat7ffJ8vNxdodu4JqQqdY5nGn0HPCkyDvcTJh6fQlF3cgSyGi4gD-GmK-vROQaEZWawZ3jzzA1QaKBLsOIlAVWBDlTtl9k2d7-eSGQREPiq269Bl7kpjXvMF_0ojM6duoOxGKpLtMZxfH-xB.js?_nc_x=O8pUiO1ZpOC:917 Uncaught DOMException: Blocked a frame with origin "https://www.facebook.com" from accessing a cross-origin frame.
    at HTMLIFrameElement.f (https://static.xx.fbcdn.net/rsrc.php/v3i8O34/yS/l/en_US/Zvbl3kzLe2vCsqT4Yp0DUqhCR7p9V8W-hH0ansD3jSLacDPUgWq3K0dw7kKDrPxyB321svkY5Nq25jlDq5g0X89Tv9bXKu_GbAxeWoyEaUZwQnVryFadZo0DqR2bHPFkrlT391tEDRB_IDmH8CsAaZNVNFzF0OkcxgBp4ptOr7_aKpw8BQAR8WMpWGat7ffJ8vNxdodu4JqQqdY5nGn0HPCkyDvcTJh6fQlF3cgSyGi4gD-GmK-vROQaEZWawZ3jzzA1QaKBLsOIlAVWBDlTtl9k2d7-eSGQREPiq269Bl7kpjXvMF_0ojM6duoOxGKpLtMZxfH-xB.js?_nc_x=O8pUiO1ZpOC:917:554)
```

EDIT: None of the buttons do anything at all.

**Comment by JadenGreen9** [comment]
You need to use this on messenger.com. If you are using facebook it won't work. Maybe this is it.

**Comment by theahura** [comment]
What Jaden said.

"The Console says nothing from the extension side" means that you're not running it on messenger.com, the extension has fairly strict permissions settings (privacy cuts both ways after all). Can you confirm which url you're using to run this?
