### ISSUE TITLE
Loaded extension on Android.. Not working

### ISSUE THREAD

**Issue by RedactedKaos** [theahura/shoot-the-messenger#18]
I currently only had access to my Android phone not really want to make use of this extension does anyone know any tricks right now you know I'm using the developer options in word to load the extension into it a mobile browser but it's not working can anyone help me out please and thank you in advance

**Comment by theahura** [comment]
Pretty sure this won't work at all in android. You can try by viewing things in desktop view, but basically you need to convince facebook that you're using a full screen to get around any CSS media query type things they're doing...which I suspect won't work. Unfortunately I don't have the bandwidth to support an android version of this.

Let me know if you figure something out, but closing this for now.

**Comment by RedactedKaos** [comment]
Damn well thank you so much for taking the time to respond back.. That
means alot
