### ISSUE TITLE
This isn't working for Unsend For Everyone

### ISSUE THREAD

**Issue by basslaboratory** [theahura/shoot-the-messenger#19]
Is there a quick script fix that can fix this?

**Comment by theahura** [comment]
Not sure what's not working from this alone. 

A few things to check. First, make sure you are using messenger.com in the URL bar. Second, make sure your language is set to english. If both of those are true and it's still not working, can you post a dump of the dev console? (hit f12, go to the console tab)

**Comment by n4ru** [comment]
+1, I just get a FB prompt that asks if I'm sure I want to remove it, and that the other parties would still see it.
