### ISSUE TITLE
I just tried it and nothing seems to happen when i click "remove messages"

### ISSUE THREAD

**Issue by HastePSD** [theahura/shoot-the-messenger#20]
not really sure why, tried on multiple conversations

tried changing between english uk and english american settings on chrome

**Comment by JadenGreen9** [comment]
Try doing it in messenger.com if you are not already.

**Comment by theahura** [comment]
Yep, what Jaden said. 

Otherwise, can you send a text dump of the console (hit f12 and go to the 'console' tab)?

**Comment by OhhKarim** [comment]
Hi, I downloaded this script and followed all steps but whenever I try to remove messages nothing happens. I tried both on facebook.com and messenger.com, tried on English UK language. The f12 console is empty. I have no knowledge about scripting, please let me know how to fix, thanks in advance.
![image (1)](https://user-images.githubusercontent.com/82740589/115132009-d8095f80-9ffc-11eb-89ca-dcce22e92af6.png)
![image (2)](https://user-images.githubusercontent.com/82740589/115132010-d8a1f600-9ffc-11eb-9792-f712f111f10f.png)

**Comment by OhhKarim** [comment]
By the way, as you can see, if I am in full screen resolution, the 'shoot the messenger' message is half out of my view, I have to put the tab in half size to be able to click on yes to get the full message like the second screenshot shows. I am running two other extensions, uBlock & FACEIT Enhancer if that could help.
