### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by nimom38** [theahura/shoot-the-messenger#22]
This extension is not working now. :( I really need this. Can you please look into this issue? I'll be forever grateful.

**Comment by nimom38** [comment]
**EDIT**
It is working fine in messenger.com
It's really cool!

By the way, is it possible to add a feature to unsend every messages in every threads using just a single click? Here, I have to go to all the threads individually.

**Comment by theahura** [comment]
The extension simulates a human user, so it would take a looooooooooooooong time. Ostensibly yes, but I don't have any plans to add that feature. If you want to give it a shot though, the extension isn't doing anything more complex than clicking HTML buttons.
