### ISSUE TITLE
Script stuck in loop "Waiting for loading messages to populate..."

### ISSUE THREAD

**Issue by vemfanvet** [theahura/shoot-the-messenger#24]
After successfully running the script for a couple of minutes it gets stuck on "Waiting for loading messages to populate..." even though messages has been loaded and the loading bar is out of view. If i manually scroll up the script continues to work for some time but it will eventually get stuck on the same message.

It also seems to get stuck in a "Clicking remove buttons:" and "Unsending" loop. Not sure if it has something to do with rate limiting from facebook?

```
main.js:153 Clicking remove buttons:  NodeList(3) [div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…, div.oajrlxb2.gs1a9yip.g5ia77u1.mtkw9kbi.tlpljxtp.qensuy8j.ppp5ayq2.goun2846.ccm00jje.s44p3ltw.mk2mc…]


main.js:165 Unsending:  NodeList(6) [div.oajrlxb2.g5ia77u1.qu0x051f.esr5mh6w.e9989ue4.r7d6kgcz.rq0escxv.nhd2j8a9.pq6dq46d.p7hjln8o.kvgmc…, div.oajrlxb2.g5ia77u1.qu0x051f.esr5mh6w.e9989ue4.r7d6kgcz.rq0escxv.rj84mg9z.pq6dq46d.p7hjln8o.kvgmc…, div.oajrlxb2.g5ia77u1.qu0x051f.esr5mh6w.e9989ue4.r7d6kgcz.rq0escxv.nhd2j8a9.pq6dq46d.p7hjln8o.kvgmc…, div.oajrlxb2.g5ia77u1.qu0x051f.esr5mh6w.e9989ue4.r7d6kgcz.rq0escxv.rj84mg9z.pq6dq46d.p7hjln8o.kvgmc…, div.oajrlxb2.g5ia77u1.qu0x051f.esr5mh6w.e9989ue4.r7d6kgcz.rq0escxv.nhd2j8a9.pq6dq46d.p7hjln8o.kvgmc…, div.oajrlxb2.g5ia77u1.qu0x051f.esr5mh6w.e9989ue4.r7d6kgcz.rq0escxv.rj84mg9z.pq6dq46d.p7hjln8o.kvgmc…]
```

**Comment by vemfanvet** [comment]
Seems to be related with rate limiting. 
If I wait around 5 minutes and start the script it works for a couple of minutes.
If i wait several hours it will work for around 30 minutes before getting stuck

**Comment by vemfanvet** [comment]
The size of my monitor also affects how fast I hit the rate limit since it loads more messages the bigger your monitor is.
On my 13" Macbook it can run for a longer amount of time than on my 27" 1440p monitor

**Comment by theahura** [comment]
I added a failsafe for the loader so that it only tries to scroll up 3x before moving on. Hopefully that should resolve this issue. Feel free to reopen if it doesnt.
