### ISSUE TITLE
Run in background?

### ISSUE THREAD

**Issue by vemfanvet** [theahura/shoot-the-messenger#25]
When the window running the script loses focus the script stops running with the following error.
Is there any way to prevent this? Trying to run in a Hyper-V VM but it stops working as soon as i either close the remote connection, click outside of the vm console or if i just run it in my own browser and change windows/tab even though i have it visible on another monitor

```
TypeError: Cannot read property 'getAttribute' of null
    at removeBadRowsFromDOM (main.js:107)
    at unsendAllVisibleMessages (main.js:117)
    at runner (main.js:212)
    at async longChain (main.js:364)
    at async removeHandler (main.js:391)
```

**Comment by theahura** [comment]
When it loses _focus_? thats interesting. The permissions are set up such that it needs to be the tab that is open, but you can generally get around this by pulling the tab off into its own window and leaving it running in the background. I've never seen this issue from just clicking off the tab though.

**Comment by vemfanvet** [comment]
Seems like it can run fine in the background, the issue was probably related to rate limiting
