### ISSUE TITLE
Warning dialog is drawn off the edge of screen when chrome is maximized

### ISSUE THREAD

**Issue by JasonJShuler** [theahura/shoot-the-messenger#27]
The warning dialog - especially the buttons - seem to be drawn relative to the extension icon - Have to press esc to to dismiss, shrink window and move substantially to the left.

**Comment by theahura** [comment]
That's super weird. By warning dialog I assume you mean the 'YOU SHOULD BACKUP YOUR DATA BEFORE USING THIS EXTENSION' alert? I think I know how to fix this but just want to confirm that that is what you mean.

**Comment by theahura** [comment]
It looks like this is actually a known problem with Chrome. See:

https://superuser.com/questions/1206959/chromes-modal-dialog-box-stuck-off-screen-how-to-move-it-back-permanently
https://stackoverflow.com/questions/9967289/chrome-alert-prompt-displays-off-the-screen
https://stackoverflow.com/questions/19529036/google-chrome-not-displaying-alert-popups-for-one-site

Right now the alert lives in popup.js (i.e. the extension window) but maybe it should live in main.js (i.e. messenger)...I can see if that fixes it.

**Comment by theahura** [comment]
It looks like switching tabs once the modal comes up will break the extension. Not sure if that is related though.

**Comment by theahura** [comment]
Do you think you could send a screenshot? I can't replicate this at all

**Comment by theahura** [comment]
Either way I'll switch to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog in the next version, hopefully this weekend but not sure when I'll get to it.

**Comment by theahura** [comment]
I think this should be fixed. Let me know if this is still an issue.
