### ISSUE TITLE
Version in Chrome extension store doesn't seem to work anymore

### ISSUE THREAD

**Issue by JasonJShuler** [theahura/shoot-the-messenger#28]
The version here in GitHub works a champ!!
The version in the Chrome store doesn't do anything after confirming the nuke

**Comment by theahura** [comment]
Huh. You're right. I'll update the package again, idk why that isn't working.

**Comment by theahura** [comment]
Submitted for review. Hopefully that fixes things.

**Comment by theahura** [comment]
Version 2.0.1 is out, hopefully that should fix any issues. Tested on my end, looks like its working. Let me know if for whatever reason it doesn't work on your end.
