### ISSUE TITLE
Suggestion: Date Range Support

### ISSUE THREAD

**Issue by JasonJShuler** [theahura/shoot-the-messenger#29]
It would be handy to be able to limit to a date range. Not necessary, but handy.

**Comment by Battle9** [comment]
Yes, I agree. 

If I scroll up for 1 week or 1 month or 10 pages and that point would be a start point. Your code can scroll up but It will scroll up if it is finished the showed content. It would be much better if it scrolls up after the start point and not when it is finished the newest messages.

**Comment by theahura** [comment]
I looked into this a bit this week and couldn't find a consistent way to easily read the timestamp of a given message. It seems like the only way to implement something like this is to keep track of the last seen datetime, but I think that would be pretty ugly to do...happy to look into this more if there's something I'm missing

**Comment by theahura** [comment]
I added an ability to start from a particular text string. It doesn't END at a text string, but I think this gets most of the way towards what this feature is trying to accomplish. LMK if this should be reopened
