### ISSUE TITLE
Stuck on Waiting for loading messages to populate and stickers can be removed

### ISSUE THREAD

**Issue by pcmester** [theahura/shoot-the-messenger#3]
Hey there,
First of all, thank you for this amazing extension, now it works almost flowlessly. So thank you very much!

Somewhy the script stucks on "Waiting for loading messages to populate", until I manually hit the scroll wheel to scroll up. Than, it works fine. I think the amount of the scroll should be adjusted some way, cause it does not scroll up maximally right now.

I think the sticker issue can be a bug, cause now url-s and stickers can be removed too.

**Comment by theahura** [comment]
Hey sorry, just saw this. Looks like it's bricked again.

I _probably_ won't be able to fix this until next week. Thanks for flagging this and sorry about the delay, been having a rough couple of months on my end.

**Comment by theahura** [comment]
Also, looks like FB readded the 'search in conversation' feature. I will probably just revert back to the old system that was using search in convo to more surgically remove only the user's messages. This will take longer, but should be better for everyone.

**Comment by pcmester** [comment]
Thank you wery much! Yes, I've just noticed that the function is back. Actually, the extension is fully functional with some auto-refreyh. Thanks for your time and for this amazing tool!

**Comment by theahura** [comment]
It looks like things are removing now. I'm working on readding the use of the search-in-convo feature, and in the process I currently removed the ability to remove every message in the chain, which means for really long message chains this will crash. However, it _should_ work with smaller chains just fine. I'll try and get the search in convo stuff in by end of week.

@pcmester if you can test this I'd appreciate it. In the meantime, closing this out, feel free to reopen if there are still issues.
