### ISSUE TITLE
Messenger throttles the unsend requests and only the messages from the other person get removed

### ISSUE THREAD

**Issue by pokojoro** [theahura/shoot-the-messenger#38]
Hi there,

I've been trying to use your extension and it seems like longer conversations have a problem. The extension works initially but after one removal of your texts it stops working. The interesting bit is that I believe Facebook (or messenger) detects the extension and disables message removal. I did some testing and while the extension is running I also cannot manually delete messages in the same conversation on my phone until I stop the extension running and do a few reloads of the page on my PC. I am using the latest GitHub downloaded version on the latest version on Chrome.

Any help would be greatly appreciated.

**Comment by Pranto333** [comment]
Faced same problem on here.

**Comment by theahura** [comment]
Ah, you're getting rate limited. This is something that facebook does to avoid spam. I might need to fiddle with the timeout settings to avoid this issue :thinking: Will look into it, thanks for opening the issue.

**Comment by pokojoro** [comment]
> Ah, you're getting rate limited. This is something that facebook does to avoid spam. I might need to fiddle with the timeout settings to avoid this issue 🤔 Will look into it, thanks for opening the issue.

Thanks please let us know when a fix is available!

**Comment by raykai** [comment]
please fix!

**Comment by programmersRuleTheWorld** [comment]
This may not be fixable, but even working within these constraints, I was able to delete all the messages I wanted, but it took a lot of work. But it does get the job done. However, now there it is completely not working and stops after displaying the "Who do you want to delete this message for? Everybody(x) You()"
Someone already opened a ticket on this but just wanted to mention it here too.

**Comment by theahura** [comment]
Ok I tried to add a fix for this by exposing a variable that you can adjust that will set the pause time between removals to try and side step rate limiting. Give this a shot, let me know how it goes.
