### ISSUE TITLE
The extension will remove only the sent images.

### ISSUE THREAD

**Issue by Pranto333** [theahura/shoot-the-messenger#39]
It will very useful for some users if you add such a feature. 
If it is not possible, you may add the feature of removing both side images.
Waiting for the feature to be added.
Thanks in advance.

**Comment by theahura** [comment]
Currently this isn't possible.

See below: 
Shoot the Messenger cannot support removing only your messages. See #33, #26, #15 for more. This is due to how Chrome manages memory, and because Facebook does not provide a mechanism to go to an arbitrary point in the conversation programmatically.
