### ISSUE TITLE
Installing unpacked extension

### ISSUE THREAD

**Issue by rayoh123** [theahura/shoot-the-messenger#4]
Hello, when I install this unpacked extension and try to use it, I get this UI. Is this normal? When I click on the button "Remove Messages" or "Scroll down Inbox" while on Messenger, nothing happens. How can I fix this? Thank you.
![Capture](https://user-images.githubusercontent.com/28518335/106332761-429bd200-623c-11eb-8fc7-554bd7430aac.PNG)

**Comment by theahura** [comment]
Yep that's normal. It's bricked right now. Fix will hopefully go up next week. See: #3
