### ISSUE TITLE
"Who do you want to unsend this message for?" -- This message is shown and the process is stopped.

### ISSUE THREAD

**Issue by ibehnam** [theahura/shoot-the-messenger#41]
**Describe the bug**
FB's "Who do you want to unsend this message for? ( x ) Unsend for everyone, (  ) Unsend for You" is shown and the process is stopped without giving any error message.

**To Reproduce**
Just start using in a group chat.

**Expected behavior**
In the message shown above, there are two buttons: "Unsend" and "Cancel". The extension must click on "Unsend" to continue.

**Screenshots**
![image](https://user-images.githubusercontent.com/58621210/126885507-3e8caddb-401b-4888-a0ac-2ba16847fa54.png)
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 92.0.4515.107 (Official Build) (64-bit)

**Logs**
---

**Comment by programmersRuleTheWorld** [comment]
Same issue.

**Comment by theahura** [comment]
Yep, I can replicate on my end. Looks like changes to the FB UI broke the extension. Will try and get a fix out ASAP.

**Comment by theahura** [comment]
Latest updates fix the issue.
