### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by parvizrovshanaliyev** [theahura/shoot-the-messenger#42]
**Shoot the Messenger cannot support removing only your messages.**
See #33, #26, #15 for more. This is due to how Chrome manages memory, and because Facebook does not provide a mechanism to go to an arbitrary point in the conversation programmatically. 

**Describe the feature you'd like**
![image](https://user-images.githubusercontent.com/44087592/126894739-d4747c2a-aeff-4a23-9d88-8f286b7a0122.png)

**Comment by theahura** [comment]
That's interesting. Thanks for the flag, a few other folks have mentioned this as well. I've been meaning to move from alerts to modals anyway, will try and fix this in the next patch

**Comment by theahura** [comment]
Latest updates fix the issue.
