### ISSUE TITLE
The extension does not work

### ISSUE THREAD

**Issue by jamec1** [theahura/shoot-the-messenger#43]
**Describe the bug**
Hi, I love the idea of this extension, I'm thankful that someone is interested in this problem. I want to leave Facebook behind, and I want to delete my messages before deleting my account. Unfortunately, when I start up the extension, it looks like it clicks on all the remove buttons, and after that, it either clicks on the confirmation button or it gets stuck. In either case, the messages do not get removed. Sometimes it removed one or two messages, but never more, regardless of how long I let it to run.

I am using the latest version of the plugin loaded manually; it yields the same result as using the release version.

Could you advise on how I could get this extension to work?

Thanks in advance.

**To Reproduce**
Open messenger.com, and start up the plugin.

**Expected behavior**
Removing all the messages automatically.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Opera
 - Version 77.0.4054.277

**Comment by theahura** [comment]
Yep, looks like updates to the messenger ui bricked the extension. Thanks for flagging it, I'll try and fix ASAP.

**Comment by theahura** [comment]
Latest updates fix the issue.
