### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by name-redacted-au** [theahura/shoot-the-messenger#44]
Hey, this is an amazing idea so I'm really keen for it to work! But, when I try to use the extension, it simply scrolls upwards and at some random point reloads the page without having removed any messages whatsoever. (Sometimes, it may remove one or two). See below what I got from F12. Thank you!

![image](https://user-images.githubusercontent.com/88924017/129439076-ba3cf6c3-dbdc-4e77-af2e-f19631a25a66.png)
![image](https://user-images.githubusercontent.com/88924017/129439102-7586a116-8795-4673-b638-f919422af6a9.png)

 - OS: macOS HighSierra 10.13.6
 - Browser: Chrome

**Comment by theahura** [comment]
Facebook broke the extension again. Looking into it, thanks for the flag.

**Comment by theahura** [comment]
It looks like the previous way of selecting the 'more options' menu is no longer valid. Specifically, FB made it so that the entire div that we used to click on is removed if the parent div is out of focus (hover?). I'm looking for ways to programmatically trigger focus/hover on all of the items at once to try and trick react to load the divs. If I can't, we're in a bad spot.

**Comment by theahura** [comment]
Even more specifically, previously we could select the menu that opened the unsend option using: 

```
holders = document.querySelectAll('[aria-label="Message actions"]')
for (holder of holders) {
  holder.click()
}
more_buttons = document.querySelectAll('[aria-label="More"]')
for (more_button of more_buttons) {
  more_button.click()
}
```

this doesnt work anymore. The 'Message actions' aria label was removed.

**Comment by MrPilotMan** [comment]
If the extension is running and the cursor hovers over a message (exposing the more menu), that message will be successfully deleted. Otherwise, nothing happens (as already stated).

**Comment by theahura** [comment]
Yes, the hover event pulls up the hidden message actions menu which in turn allows the rest of the script to run. Problem is, I can't programmatically simulate the hover event. 😞

**Comment by del77** [comment]
I managed to display the buttons using
```
document.querySelectorAll('[data-testid="message-container"]')[0]
   .dispatchEvent(new MouseEvent('mouseover', { 'bubbles': true }));
```
Isn't it something that could be used here?

**Comment by theahura** [comment]
Nice! The `bubbles` parameter is what I was missing. I'll try a rewrite using that, I think that should put us back in business

**Comment by del77** [comment]
Good to hear that. Waiting for the update. :)

**Comment by theahura** [comment]
I've started a rewrite, but it's taking longer than expected in part because I'm on a wicked dose of antibiotics right now. Will try to get it up this weekend.

**Comment by del77** [comment]
Sure, hope you get better soon!

**Comment by programmersRuleTheWorld** [comment]
This comment chain is why I love open source software.
Thanks guys. :)
This is a great extension.

**Comment by r1bnc** [comment]
Gws

**Comment by theahura** [comment]
Working on this today, hopefully can get a rewrite in. One thing I want to pitch to the crowd: if anyone can figure out how to simulate an 'enter' keypress on the 'Search in Conversation' element, I could rebuild Shoot the Messenger to only delete your messages instead of everyone's. (This is how StM used to work, but i can't trigger the enter key on the search anymore)

**Comment by theahura** [comment]
See #46

**Comment by theahura** [comment]
Annnd done. Published to chrome webstore as well but its currently in review, might take a day. Let me know if you run into any bugs.

**Comment by asierra2z** [comment]
hi any update? been trying to use it but it always shows failed to complete and error. any idea why?

**Comment by theahura** [comment]
You're going to have be more specific. Can you open a new issue here and post more information about what isn't working?
