### ISSUE TITLE
Confirmation popup keeps interrupting the deletion

### ISSUE THREAD

**Issue by Chene-mou** [theahura/shoot-the-messenger#45]
Hi, I keep getting this confirmation popup when the plugin starts to remove messages it seems to stop the proccess if I don't click 'OK' but the message keeps coming every 30 seconds 

![tquDUvX](https://user-images.githubusercontent.com/56235593/131217916-214daa1c-4cd6-4ded-9b18-0975be4230ee.png)

thank you for this great plugin Amol!

**Comment by r1bnc** [comment]
Is it working for you? I think the extension is broken at the moment see, https://github.com/theahura/shoot-the-messenger/issues/44

**Comment by Chene-mou** [comment]
> Is it working for you? I think the extension is broken at the moment see, #44

it's definetly spotty but it does work

**Comment by theahura** [comment]
Interesting. A lot of people are getting problems as per #44. If this is working for you, can you post your chrome version and maybe your system specs?

**Comment by theahura** [comment]
Closing with most recent push + lack of activity
