### ISSUE TITLE
Only remove your messages

### ISSUE THREAD

**Issue by theahura** [theahura/shoot-the-messenger#46]
Currently, Shoot the Messenger cannot support removing only your messages. See #33, #26, #15 for a full description. This is due to how Chrome manages memory, and because Facebook does not provide a mechanism to go to an arbitrary point in the conversation programmatically. 

However, at one point StM did have a way to only remove your messages. The way it did this was by using the Search in Conversation feature to checkpoint where the deletion script was in the chat. It would then refresh the page, and use the saved checkpoint to return back to where it was previously deleting.

The old code would trigger an 'enter' keypress on the Search in Conversation element. I cannot figure out how to do that anymore. Open to suggestions!

(See [this commit](https://github.com/theahura/shoot-the-messenger/tree/54c36aec0f3c91565f5da8e8890fac987fb40185) for the last time StM worked using the Search in Convo feature)

**Comment by r1bnc** [comment]
This could be unrelated to the project but I just want to call your attention, if you for example use something like Matrix with mautrix-facebook bridge (https://github.com/mautrix/facebook) using your own matrix server (easiest guide is https://github.com/spantaleev/matrix-docker-ansible-deploy) your deleted message in matrix will be synced to the Messenger (only your own messages). I don't know if there is an API to delete messages using matrix then it should make removing messages to messenger faster. But this is just an idea for another project.

Thank you for this project.

**Comment by theahura** [comment]
Interesting. A few thoughts:
- the core value proposition of StM is that it also unsends from the receiver. Does matrix support this? 
- by using an extension it's really easy for a non-technical person to use StM (caveating that the extension is buggy as hell, but persistence is a virtue). Would I have to move away from an extension setup to use matrix?

**Comment by r1bnc** [comment]
* Yes, you can unsend your own messages but you can't unsent other people's messages.
1. For each of your message
![image](https://user-images.githubusercontent.com/8337343/131301519-820dd436-44a8-450e-a2af-bda81ff759c2.png)
2. After clicking Remove
![image](https://user-images.githubusercontent.com/8337343/131301490-73f04da6-cb1b-4f6a-86be-0e3c2f816c1f.png)

* I agree this extension is the easiest one without any other setups. It could not be feasible for others who doesn't use Matrix.

**Comment by r1bnc** [comment]
Hi again, I want to ask if you will be planning for the addon to support Mozilla Firefox?

**Comment by theahura** [comment]
Not really related to this thread. 
I'm not currently planning to add Firefox support. I imagine it wouldn't be too hard though, can you open a feature request?

**Comment by del77** [comment]
@theahura, do you have an idea how we could speed up the process of messages removal? It takes a lot of time when it's done one be one and own messages need to be deleted two times.

**Comment by theahura** [comment]
This also isn't really related to this thread. Please open a new feature request. The short answer is, this isn't doable due to changes in the fb UI discussed in #44

**Comment by bluevex** [comment]
I'm a bit confused at why this isn't possible if this program can bypass unremovable things, like ${STICKER_QUERY}, ${LINK_QUERY}, ${THUMBS_UP}. Can't a rule just be added to the "Removing bad rows from dom" part, that also marks all left justified messages, or rows that contain a profile picture (since your rows don't have one)?

**Comment by bluevex** [comment]
Relatedly, it seems the ability to search facebook messages is still there, albeit with an extra mouse click or two. Can we just revert to the previous way that the program dealt with the chrome memory issue? I'm not sure how they "updated it to prevent it from being programmatically used", but if they like make something change everytime you use it, the mouse click positions are the same at least, so could that be used?

**Comment by theahura** [comment]
It depends on how far back you want your messages to be deleted. Messages that aren't deleted stay around in memory even if they are hidden, which means eventually your browser will crash. The only way I've found around this is to periodically automatically refresh the page. But refreshing only goes so far, and eventually even refreshing will fail due to the amount of hidden messages. By deleting every message, the extension avoids this issue. 

Previously I had the extension use the search in conversation feature to jump ahead after a refresh to where it previously left off. The jumping ahead allowed the extension to continue without incurring the memory cost of all previous messages, which in turn allowed the extension to be more selective about what was removed. 

In theory we could hide the self messages, but for my use case it was better to be able to delete all of my messages (even if it meant deleting all of their messages too) than it was to only delete some of my messages and leaving all of theirs.

**Comment by bluevex** [comment]
So it seems the following needs to be done in JS:

1. Fill "Search Messenger" text box with search term, wait for "Search Messenger for "X"" element to appear
2. Click "Search Messenger for "X"" element

This seems to bring me to the most recent message matching that term, with no messages loaded after that. Did you try this and get inconsistent behavior with the actual search?

In the meantime, how about this as a workaround? (This could be a switch in the extension for people who prefer it the current way. The current way is weird for me since they still have a copy of their messages, so you're removing information from yourself.)

1. Start deleting only messages sent by yourself from most recent. Each message deletion, record the text of the chat partners nearest text in a text file or some other static thing, overwriting the previous one.
2. When chrome crashes, the user reopens it, searches for the recorded message manually, and now the chat history starts from that point and can be scrolled back.
3. Rerun the extension.

It's annoying to have a manual step, but if months can be done at a time it is still extremely useful, and this seems simple to implement if you already have the code to only delete self messages from last year.

**Comment by theahura** [comment]
For the first part, I've tried it many different ways and haven't figured out how to make it work. Specifically, I can't figure out how to trigger a enter key event on the search box programmatically. If you can do this, please post a code fragment.

The second is definitely doable, but I was trying to avoid any manual step because I want this to run overnight without me thinking about it. 

If you want to save your messages, you can always export them.

**Comment by bluevex** [comment]
Hmm, I didn't need to send enter.

First, I did:
`javascript:(function(){document.getElementsByClassName("oajrlxb2 rq0escxv f1sip0of hidtqoto e70eycc3 lzcic4wl hzawbc8m ijkhr0an aaoq3grb sgqwj88q b3i9ofy5 oo9gr5id b1f16np4 hdh3q7d8 dwo3fsh8 qu0x051f esr5mh6w e9989ue4 r7d6kgcz br7hx15l h2jyy9rg n3ddgdk9 owxd89k7 ihxqhq3m jq4qci2q k4urcfbm iu8raji3 tv7at329 l60d2q6s d1544ag0 hwnh5xvq fjf4s8hc aj8hi1zk r4fl40cc kd8v7px7 m07ooulj mzan44vs")[0].focus()})()`

Then, I was focused and my cursor was in the text field.

Then, I typed a string.

Then, I did 
`javascript:(function(){document.getElementsByClassName("d2edcug0 hpfvmrgz qv66sw1b c1et5uql lr9zc1uh jq4qci2q a3bd9o3v b1v8xokw oo9gr5id")[0].click()})()`
to click the "search in conversation" element.

and that brought me to the most recent occurrence of that string. If typing the string is the problem, would this implementation help? https://stackoverflow.com/a/65167751

**Comment by theahura** [comment]
Can you send screenshots? neither of the snippets you posted above work in my messenger console. 

Specifically, I don't have any 'search in conversation' button to click, and that specific query by class name returns an empty list for me. Are you using messenger (as in, www.messenger.com)? its possible this a fb A/B test?

**Comment by bluevex** [comment]
Oh, those are URI-decoded Chrome bookmarklets. I'm not a native chrome developer, or a coder really, so I just put the javascript into this [Chrome bookmarklet creator](https://mrcoles.com/bookmarklet/).

To reproduce this, just enter `document.getElementsByClassName("oajrlxb2 rq0escxv f1sip0of hidtqoto e70eycc3 lzcic4wl hzawbc8m ijkhr0an aaoq3grb sgqwj88q b3i9ofy5 oo9gr5id b1f16np4 hdh3q7d8 dwo3fsh8 qu0x051f esr5mh6w e9989ue4 r7d6kgcz br7hx15l h2jyy9rg n3ddgdk9 owxd89k7 ihxqhq3m jq4qci2q k4urcfbm iu8raji3 tv7at329 l60d2q6s d1544ag0 hwnh5xvq fjf4s8hc aj8hi1zk r4fl40cc kd8v7px7 m07ooulj mzan44vs")[0].focus()` into the prompt on the site, and then it gives you a button you can drag to your bookmarks toolbar that when pressed while you're at the default messenger.com page with any conversation open, enters the search bar focus and gives a cursor:
![Captursdsdde](https://user-images.githubusercontent.com/5505910/142566749-019f6d6d-2a73-403b-9dfd-4f0dfbe0f631.PNG)

Then after typing a string, to reproduce the second one, do the same thing on that site but with the javascript code `document.getElementsByClassName("d2edcug0 hpfvmrgz qv66sw1b c1et5uql lr9zc1uh jq4qci2q a3bd9o3v b1v8xokw oo9gr5id")[0].click()` which performs the search for most recent message:

![Captdssdure](https://user-images.githubusercontent.com/5505910/142566970-434967ca-b204-4f48-9902-ff369cc462a9.PNG)

If your element names are different, they could be different per user? I found the first one by right clicking in the search text box and clicking inspect, which brought up this:
![Capture1](https://user-images.githubusercontent.com/5505910/142567135-28002622-ccfc-4707-a25a-3398a248294e.PNG)

And the second one by right clicking the "Search messages for "X"" button and clicking inspect, which brought up this:
![Capture2](https://user-images.githubusercontent.com/5505910/142567183-4111a057-41ab-44ab-b0ae-629007cdb249.PNG)

If your messenger code looks totally different than this, perhaps they are A/B testing?

**Comment by theahura** [comment]
holy shit. That totally works. 

Wow, that has to be the dumbest fucking UI pattern I've ever seen. If I understand this right, searching from the left-hand bar that is clearly meant to filter the actual message chats down by user somehow triggers a 'search in conversation' on the currently selected message chain. 

BUT! it doesn't matter, this works. @bluevex you're a genius. I'll see if I can rewrite the extension to utilize this pattern sooner rather than later. It's probably not going to happen until after thanksgiving, but at least now there's a way forward :smile:

**Comment by bluevex** [comment]
haha, thanks! I'm totally not a genius and really don't have any idea about what's going on, I just googled how to focus and click on things in JS.  Perhaps it would be cool to have a switch in the rewrite so people can choose to delete their own messages or not.

**Comment by bluevex** [comment]
Is there anything I can do to help this effort?

**Comment by theahura** [comment]
Appreciate the offer.

The most recent commit has an early build of remove-only-your-messages. I haven't really battle tested it yet, and I know it crashes in at least some cases. If you want to help, you could download the early build and start playing with it, see if it works. I expect to finish all the testing (to my own satisfaction, anyway) by next week

**Comment by theahura** [comment]
Closed with the most recent commit. Will push to Google webstore by end of week.
