### ISSUE TITLE
Reloads chrome after a few hour

### ISSUE THREAD

**Issue by kimonstavrou** [theahura/shoot-the-messenger#48]
Hi. Good try but I face the following issue with last version 4.0.1. in google chrome x64 93.0.4577.63 windows 10 pro x64
After a few hour (totally random, sometimes 1-2 minutes, sometimes after almost an hour) the operation breaks and the messenger webpage asks to be reloaded. Is it something i can do in order to fix it or it a general problem?

**Comment by theahura** [comment]
This is intended behavior. The short version is that the extension needs to clear the memory of the browser to avoid crashes.

After a reload it should continue unsending. Is the latter not happening?

**Comment by theahura** [comment]
Ok, yep this is a bug. This happens because one of the messages that got deleted is a 'hook' that facebook uses to load more messages next to/near. Are you using the latest version? Can you post a console log of what happens beforehand? How frequently does this occur?

**Comment by kimonstavrou** [comment]
Sorry for my delayed answer but I had to catch up few things here. I am using the latest version of both your extension (4.0.1) and chrome (94.0.4606.81 (Official Build) (64-bit)). I attach a console log after the crash. In the specific team chat i try to clean, it happens all the time.
![image](https://user-images.githubusercontent.com/44234882/137906643-955564a6-f8a0-4d42-8abe-2fbf79320587.png)

**Comment by ErikPrantare** [comment]
This also seems to be an issue with links

**Comment by theahura** [comment]
I'm going to be rewriting the entire extension as per #46. Should resolve this issue as well. I was hoping to get started on that last week but running your own startup is a busy time :sweat_smile: hopefully with the holidays coming up I'll have this up and running

**Comment by ErikPrantare** [comment]
Nice! Don't feel pressured, I'm happy to have this at all and only needing to manually remove links and thumbs-up ;)

**Comment by theahura** [comment]
Closed with most recent push
