### ISSUE TITLE
Runs for 25 cycles and then stops

### ISSUE THREAD

**Issue by narjekdjcusbe** [theahura/shoot-the-messenger#49]
Running Shoot The Messenger Beta 5 on Chrome Version 96.0.4664.110 (Official Build) (64-bit)

It runs (skipping the odd message) for 24 cycles.

On cycle 25 it stops and hangs until manually restarted. It can be restarted immediately without refreshing and without seeming to cause issues.

[Shoot-the-messenger.log](https://github.com/theahura/shoot-the-messenger/files/7747752/Shoot-the-messenger.log)

PS - Version number is still listed as 4.0.1

**Comment by narjekdjcusbe** [comment]
Update: While you can restart removal immediately without refresh, if you close and come back to it, then it will scroll up for a little bit until it eventually stops without removing anything - by the looks of things it's because the last "real" message needing removal is more than 25 refreshes away.

[Shoot-the-messenger-2.log](https://github.com/theahura/shoot-the-messenger/files/7747864/Shoot-the-messenger-2.log)

**Comment by theahura** [comment]
Same response as what I said on #50, you're definitely on the newest github version. It's not tested at all, very much a beta, so I need to go in and fix it.

**Comment by theahura** [comment]
Just pushed a fix for this. Should work. Please test and let me know!
