### ISSUE TITLE
Any update on when this will be working again?

### ISSUE THREAD

**Issue by conjohnerton** [theahura/shoot-the-messenger#5]
A friend and I found your extension and it looks like it's exactly what we have been looking for. Any way we can support you? We're both devs.

**Comment by johnr365** [comment]
Curious on the answer to this also - am keen to use the extension! Thanks

**Comment by theahura** [comment]
Hey folks! Yea, I really appreciate the interest. Apologies about delays on my end, life gets in the way. 

It's kinda hard to break things down into single small tasks, frankly there isn't that much code. If you want to take a stab at it, I can give you the logic flow of what needs to be done. 

Basically:
```
if (load(next_search_text))
  search(next_search_text)

for (10)
  remove_messages()
  next_search_text = get_next_search_text()
  if (do_refresh)
    save(next_search_text) // probably by sending it to the backend
    refresh page
  else:
     go back to the bottom
  search(next_search_text)
```  

Some of this logic is already complete, e.g. removing messages. I used to have the searching stuff working, but facebook borked the UI for a while. I can't give a timeline for when I'll actually get to this, but hopefully it's soon. In the meantime, though, feel free to take a stab.

**Comment by theahura** [comment]
Ok I think it should work again. Please take a look, let me know if anything else needs doing.

**Comment by conjohnerton** [comment]
You're awesome. I forgot to check back and attempt to update the code. I did, however, make a PR on your old remove comments repo!
