### ISSUE TITLE
Non functional / Skipping Messages - Facebook update?

### ISSUE THREAD

**Issue by narjekdjcusbe** [theahura/shoot-the-messenger#53]
5.0.2 is no longer functional for me - it simply scrolls endlessly without removing, and will continue to scroll without removing until it either stops when it hits the first message of the thread, or crashes. There is no popup (Remove for all / Remove for me) just constant scrolling.

It doesn't appear to be rate limiting - I can still remove messages manually - but I can't fully rule it out. From the logs it seems like it can't find how to trigger the popup, but I'm not fully familiar with them.

Attached is logs from when it's crashed before it hits the end.

[www.messenger.com-1642681393828.log](https://github.com/theahura/shoot-the-messenger/files/7905231/www.messenger.com-1642681393828.log)
.

**Comment by theahura** [comment]
Facebook may have changed the UI selectors. I'll take a look this weekend

**Comment by theahura** [comment]
Updated with version 5.0.3. Check and confirm that it works please!

**Comment by bryantwilliam** [comment]
Still doesn't work

**Comment by theahura** [comment]
Correct. I published the change but it hasn't been approved by chrome/Google yet. Will post on Twitter when it does

**Comment by bryantwilliam** [comment]
> Correct. I published the change but it hasn't been approved by chrome/Google yet. Will post on Twitter when it does

Tested 5.0.03 version by cloning. Works.

**Comment by theahura** [comment]
Latest version is out on chrome webstore. Closing this. Thanks for the reports!
