### ISSUE TITLE
Extension not doing anything for me

### ISSUE THREAD

**Issue by markzic-priv** [theahura/shoot-the-messenger#55]
Attempting to use the extension as described, nothing is happening.

I go to messenger.com and click on the extension, click delete messages, and nothing occurs. Attached screenshot after clicking the remove messages button and waiting for at least a minute.
![shoot the messenger issue](https://user-images.githubusercontent.com/96713278/151227397-a1065d71-9cda-44a9-a30e-798611d4d077.png)

**Comment by theahura** [comment]
Which version of the extension are you using? Make sure you're on 5.0.3 or the latest on github. It works for me currently, just testing in my own browser.

**Comment by markzic-priv** [comment]
5.0.3 -- Closed and reopened browser and now it works, though I'm having a similar issue to the "failed to complete removal" issue others reported from a while ago. Rerunning the extension seems to continue deleting messages, though not completely in order.

**Comment by theahura** [comment]
'Failed to complete removal' is a catch all, that could be anything. Hard to tell what's going on without the logs.

**Comment by markzic-priv** [comment]
Okay, sorry, I'm not the person to ask. Working okay for me. I'll close with comment.
