### ISSUE TITLE
Great tool, but it doesn`t unsend messages, it only removes them for me.

### ISSUE THREAD

**Issue by MegaDorijan123** [theahura/shoot-the-messenger#57]
I'm trying to unsend messages but it looks like it triggers remove for you and not unsend. Any chance of switching it up. Everything else works fine.

**Comment by theahura** [comment]
Hmmm thats no good. I'll take a look, thanks for flagging. Can you send screenshots or logs?

**Comment by MegaDorijan123** [comment]
Well, now it switched to unsend for everyone. Hmm weird, but it doesn't delete some of the messages.
https://ibb.co/kQHHKCN
https://ibb.co/tM5yVrM

**Comment by GalacticKitenn** [comment]
It triggers the "remove for you" too

**Comment by theahura** [comment]
I'm a bit confused. In both of the screenshots it looks like it's doing the right thing -- specifically, unsending the message. Can you get a screenshot where it's hitting 'remove for you'?

It is interesting that its skipping some but that's not as crazy, or at least I've seen that before. But just for clarity, is the issue that its hitting 'remove for you' or that its skipping some messages?

**Comment by MegaDorijan123** [comment]
Yes. https://ibb.co/xfzFHtb   So it unsends for everyone then like every 3rd message it just removes for me and than back to unsend for everyone and again after 2 messages remove for you.

**Comment by MegaDorijan123** [comment]
Also look how it skipped a couple of messages. I don't know why.

**Comment by theahura** [comment]
i think i know whats happening -- StM needs full control of the mouse to work. Sometimes, if your cursor is hovering over the messages as they are being deleted, the hover event will override whatever StM is trying to do. In particular, you will notice on messenger that when you hover over a message you get a 3 dot menu. Triggering that over the wrong message will cause it to skip; triggering that over a message that has already been unsent will cause it to get removed. 

Can you try StM again, but with your mouse entirely off screen?

**Comment by xtevez** [comment]
Same behavior here, it only removes for me and does *NOT* unsend for everyone.

**Comment by theahura** [comment]
Can you provide screenshots? And which version of StM are you on?

**Comment by xtevez** [comment]
Hello @theahura,
I stand corrected, the extension works great in "general" cases.

My problem: I was trying to unsend messages to a chat where the target account was either removed or suspended. In that case, "unsend" is actually unavailable in messenger itself.

One little annoyance: the first message of each chat is not unsent with the extension, but it can be done manually. No biggie.

Bug on FB side: chat messages with links cannot be unsent. The option is there, but messages simply persist. Sometimes, the thumbs up emoji (dedicated button) is also not unsend-able.

Overall, great work, thank you! :)

**Comment by theahura** [comment]
Ah, yep, that's a known issue. I should update the description to make that clear. 

Same with the links and the emojis and stickers, also a known issue on facebooks side
