### ISSUE TITLE
Rate limit pause

### ISSUE THREAD

**Issue by Kaczuc** [theahura/shoot-the-messenger#59]
How I can change rate limit pause?

**Comment by theahura** [comment]
This is something a few folks have been asking for. I'll add it to my todo list, but not sure when I can get to it. If you want to do this programmatically, simply change the DELAY variable in main.js (https://github.com/theahura/shoot-the-messenger/blob/main/main.js#L50)

**Comment by theahura** [comment]
Closed with the latest
