### ISSUE TITLE
Works well in messenger.com but after scrolling up for a while, after a 100 messages or so, the page refreshes and sends the screen all the way back to the bottom of the message chain and will have to scroll up all the way again over and over

### ISSUE THREAD

**Issue by whoc7426** [theahura/shoot-the-messenger#6]
Is there a way to disable this refreshing and just keep scrolling up?

**Comment by theahura** [comment]
Nope, this is done to avoid memory overloads. I fixed up the script so that it removes all messages, meaning on refresh it should do the right thing.
