### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by tanzimhasan01** [theahura/shoot-the-messenger#62]
It is not working on Chrome Version: 102.0.5005.115 (Official Build) (64-bit)

**Comment by theahura** [comment]
Works on my end. Can you get logs or screenshots or a more descriptive explanation of what you mean?

**Comment by tanzimhasan01** [comment]
Sorry
It's working now
But sometimes it tries to unsend received messages and gets stuck

**Comment by theahura** [comment]
Make sure your mouse isn't hovering on anything, that can trip the extension up
