### ISSUE TITLE
Feature to remove ALL messages (not just my own)

### ISSUE THREAD

**Issue by a-asen** [theahura/shoot-the-messenger#64]
When I first installed the app it removed both others messages and my own. However, when I use the app now it only removes my own messages. 

I am wondering if it could be possible to add another button to remove ALL messages (specifically) and not just my own. 
This because the memory usage increase as more messages gets loaded -- especially problematic in LONG chats.

This would significantly help in removing my own messages as they are, sometimes, so far up in the chat that it takes forever to load them in (scrolling past so many messages). 

Otherwise great app, thanks!

**Comment by theahura** [comment]
Interesting, the extension should refresh the page and search for the last deleted message to avoid exactly that situation of memory usage.

You can always 'warm start' by running a search yourself, and then starting the extension from there. But I am curious -- if the extension is not refreshing after going up for a real long time, this is a bug

**Comment by a-asen** [comment]
Oh, curious... I do not believe my app has ever done that... 
(2 min later) 
Speak of the devil. It just did search for an old message and started searching from there. It still had to search quite far up before finding any messages, but significantly better than from the very start (heh). 

I do find it curious because I have never seen the app do that...

Will the app, after a while, refresh "to easy the load on memory", or is that something that has to be done manually (if anything?).  If manual: Will it remember the "last" loaded message, search for it, and start searching from there? 

I still think a "remove all messages" is a fair feature -- I at least would like it :)

**Comment by theahura** [comment]
sorry i thought I responded to this -- the app is supposed to do all this automatically. It remembers the last loaded message and all that without having the user do anything. I wrote this originally to run overnight so I didn't have to think about it.

Did this keep breaking for you or does it work?

**Comment by a-asen** [comment]
No, that feature works.
