### ISSUE TITLE
Question: Chat History

### ISSUE THREAD

**Issue by gamesswitch** [theahura/shoot-the-messenger#65]
Hi,
Extension was working fine, but only deleted about 10 days worth of conversation and then it stopped, (refreshes page and doesn't goo any further)
is there any way to go further back?
Thank you

**Comment by theahura** [comment]
It should automatically open the search and go forward on its own. I can take a look at this to see if I can replicate on my end, but it's probably not going to be for a while.

Sometimes the extension gets buggy if your mouse is hovering over things -- is your mouse on the screen when you're using it?

**Comment by gamesswitch** [comment]
Mouse is not the issue, I left it alone and yes it goes forward on its own but to a certain point and then it refreshes the page and stops. If you could test it when possible that would be great.

**Comment by theahura** [comment]
Going to merge this with #60
