### ISSUE TITLE
ERROR: something went wrong. Failed to complete removal.

### ISSUE THREAD

**Issue by Vexinize** [theahura/shoot-the-messenger#66]
Hello,

Apologies just going to layman describe the issue. I tried both the extension from the store and removed and tried the developer unpacking. However, each time I try to do it it just gives me an error 

It deleted maybe one or two messages, then also started appearing to unsend for just me and warned me that others will still be able to see the message then drops the error message. Or when I try restarting closing things out and going back in it just gives me the error from the get go. I am just not touching my mouse and not hovering over the website.

"ERROR: something went wrong. Failed to complete removal."

Thanks for putting the effort into creating something like this. Really appreciate it! Certainly will buy you a coffee if it starts working soon :)

**Comment by theahura** [comment]
Ok looks like something is going on since I've gotten a few of these reports. Going to merge this with #65 and #60
