### ISSUE TITLE
extension broken?

### ISSUE THREAD

**Issue by elotulapka** [theahura/shoot-the-messenger#69]
scrolls up in a chat but never clicks unsend on messages, and gives an error when it reaches the top of the chat

i used it yesterday and it worked fine! i don't know if this issue impacts all users. also thanks for developing this amazing script, it really saves my life

**Comment by LifelessLife** [comment]
Yup! need to update. Just wait for new version.  Facebook mess with code on Messenger (sidebar).

**Comment by theahura** [comment]
Thanks for the error report -- will have to take a look. It's a busy few weeks for me though so no promise that it will come that soon :grimacing:

**Comment by theahura** [comment]
@anderseee thanks so much for the patch!

**Comment by theahura** [comment]
Updated the version and am pushing the update to the chrome store!
