### ISSUE TITLE
STM fails with small number of messages

### ISSUE THREAD

**Issue by theahura** [theahura/shoot-the-messenger#72]
If you have a small number of messages in a chat, such that there is no scroll bar, shoot the messenger fails. See #60.

**Comment by MuttakinHasib** [comment]
@theahura  how can I remove messages from both sides?

**Comment by theahura** [comment]
@MuttakinHasib please open a new issue

**Comment by 10SecSleeper** [comment]
I'm not able to recreate this issue. Even if there's only one comment made on our end, it gets deleted once it finds top of chain.

**Comment by theahura** [comment]
closing due to staleness
