### ISSUE TITLE
This extension can not remove the other side's message

### ISSUE THREAD

**Issue by MuttakinHasib** [theahura/shoot-the-messenger#73]
![image](https://user-images.githubusercontent.com/44552983/195900092-b895a338-3e1c-4133-99a2-814a1c95298c.png)

**Comment by MuttakinHasib** [comment]
@theahura please help me

**Comment by theahura** [comment]
@MuttakinHasib I'm confused what you're trying to do. What is the benefit of removing the OTHER persons messages?

**Comment by MuttakinHasib** [comment]
I can't delete this conversation; there is no delete or archive option
Maybe this account has been deleted or disabled...

But when I hover over any message in this conversation, there are ‘more’ options that have ‘remove.’ 

I hope you understand what I am saying

**Comment by theahura** [comment]
im not fully sure i understand.

Shoot the Messenger is a tool that automatically hits the 'unsend' button on each message in a messenger chain. You can only 'unsend' your own messages. Unsending a message removes that message from the receivers inbox. 

If you delete a message that the other person sends you, it doesn't really get unsent; it only 'hides' the message from your inbox. The other person's inbox will still contain the message. As a result, I'm having a tough time understanding why this is useful. 

Facebook does have tools that let you archive or delete entire conversations, but it sounds like thats not working for you? unfortunately i dont know why, but i think its out of scope for this app

**Comment by hyperarcher** [comment]
When you can't send messages to conversation, which happen when :
- The account was deleted or deactivated
- The other end blocked your profile or blocked you from messaging them
- You blocked the other end

Then you won't be able to unsend messages
