### ISSUE TITLE
Messenger no longer showing "unsend for everyone" as an option

### ISSUE THREAD

**Issue by keveguo** [theahura/shoot-the-messenger#74]
Hi Dev,

Thanks for all your hard work on this extension so far, 

just noting that messenger.com no longer allows users to "unsend for everyone" when you click on the three dots. 

The only option available is "remove for you"

![image](https://user-images.githubusercontent.com/106779619/196008572-45272ec1-e428-429b-9f38-aaf56f5c90e2.png)

facebook.com/messages is a good alternative that still allows "unsend for everyone"

![image](https://user-images.githubusercontent.com/106779619/196008649-80bcaabf-7df2-4388-9141-7aeec4f74d9a.png)

would you be able to somehow update the extension to also work on facebook.com/messages?

Thanks!

**Comment by theahura** [comment]
> just noting that messenger.com no longer allows users to "unsend for everyone" when you click on the three dots.

Are you sure? I just tried this on my end and it worked fine. 

> would you be able to somehow update the extension to also work on facebook.com/messages?

probably not, too much extra work juggling the html selectors whenever they get changed. Might look into it if it turns out messenger really _isnt_ allowing removal.

**Comment by theahura** [comment]
closing this since I haven't heard anything back
