### ISSUE TITLE
Rate limit doesn’t affect speed of deletion 

### ISSUE THREAD

**Issue by rayoh123** [theahura/shoot-the-messenger#77]
The rate limit input box doesn’t affect the speed at which messages are deleted. I put two seconds in the rate limit box and the speed of deletion was still instantaneous.

**Comment by theahura** [comment]
It should slow down the rate of deletions _between_ scrolling upwards. I found that was sufficient, and mass deletion was still fast. Are you running into roadblocks?

**Comment by 10SecSleeper** [comment]
I had the latest build run for 4 hours and not once did it start having  unsent failures.

It's possible to make changes to have it take a short break if messages stop getting unsent. In previous builds I had to pause it manually 10-15 minutes and once resumed the messages were unsent upon attempt.
