### ISSUE TITLE
Cannot use 'in' operator to search for 'scrollTop' in null

### ISSUE THREAD

**Issue by maciex** [theahura/shoot-the-messenger#78]
**Describe the bug**
Extension did work few times during the tests. But after few tries it stopped working. Errors being logged in dev console.

**To Reproduce**
1. Open one of the Messenger chats
2. Run the removal using "Remove messages"
3. Confirm deletion in the query window
4. Nothing happens
5. See error in console

**Expected behavior**
Messages deleted in the chat.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium 106.0.5249.119 
 - Browser 2: Google Chrome stable 107.0.5304.87

**Logs**
 ```
Got action:  REMOVE
5The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
main.js:257 Starting runner removal for N iterations:  10
main.js:259 Running count: 
Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'scrollTop' in null
    at getScroller (main.js:71:24)
    at prepareDOMForRemoval (main.js:119:3)
    at unsendAllVisibleMessages (main.js:148:36)
    at runner (main.js:260:29)
    at removeHandler (main.js:362:24)
    ```

**Comment by maciex** [comment]
It seems that `el` is `null` in that are.
I did a quick debug and it seems the `document.querySelector()` method returns `null`:

```
ROW_QUERY = '[data-testid="message-container"]';
> '[data-testid="message-container"]'
let el = document.querySelector(ROW_QUERY);
> undefined
```

I also checked on other chats, but got the same `null` result

**Comment by theahura** [comment]
Thanks for the clear replication of the bug. I'm running into issues on my end as well so I can replicate. I'll try and fix this soon but as usual super busy. Might be able to do this next weekend

**Comment by maciex** [comment]
@theahura let me know if there's any code or even a snippet I could check (I can rerun it in dev mode).

**Comment by theahura** [comment]
I'm almost positive this is a simple bugfix. There's a list of queries at the top of main.js, one of those queries is no longer valid (probably the one for ROW), and I just need to replace it with a query that _does_ work
https://github.com/theahura/shoot-the-messenger/blob/main/main.js#L8

**Comment by 10SecSleeper** [comment]
I changed l7 and l8 with the following, It works, but it removes all messages. Not seeing the easy fix. Not sure how it worked before. I might be missing something obvious.

ROW_QUERY = '.x63ui4o.x18i3tt1.x6ikm8r.x10wlt62';
MY_ROW_QUERY = '.__fb-light-mode.x1n2onr6';

**Comment by maciex** [comment]
This worked for me. I mean most of the messages were unsent.
The script ended with error in console (keep in mind that I added the new queries as new lines, so the line numbers are shifted +2):
```
main.js:206 Removed all holders.
main.js:242 No scroller or load buttons, but we didnt hit the top. Failing.
main.js:384 Failed to complete removal.
```

Also one of the messages in the chat was not deleted (this is the first message in the conversation).

**Comment by maciex** [comment]
It seems the script has problems with detecting that new messages should be loaded or we're not on the top message.

I tricked the script to go through all the messages but not delete them. And it fails with the same message (this time the lines should match the source code in `master`):
```
main.js:204 Removed all holders.
main.js:240 No scroller or load buttons, but we didnt hit the top. Failing.
main.js:382 Failed to complete removal.
```

**Comment by theahura** [comment]
I think this means the MESSAGE_CONTAINER_QUERY is also busted

**Comment by 10SecSleeper** [comment]
> It seems the script has problems with detecting that new messages should be loaded or we're not on the top message.
> 
> I tricked the script to go through all the messages but not delete them. And it fails with the same message (this time the lines should match the source code in `master`):
> 
> ```
> main.js:204 Removed all holders.
> main.js:240 No scroller or load buttons, but we didnt hit the top. Failing.
> main.js:382 Failed to complete removal.
> ```

I opened a pull request with a version that should fix all current issues.

**Comment by theahura** [comment]
Merged. Thanks a ton @10SecSleeper !
