### ISSUE TITLE
I know you said that it should also delete the messages that others send you but it actually doesn't do that unless you manually make the remove|forward menu appear on their messages. Actually I would like to also remove the messages of others (I know it will be "remove for you only" and that's fine) 

### ISSUE THREAD

**Issue by whoc7426** [theahura/shoot-the-messenger#8]
Basically what I mean by this is that I want to delete "for me" all the messages that the other person sent me, that doesn't work automatically even though you warn against it happening and how it's important to back up the chat before activating the script. But .. that's not working though.. I would like it to work :(

**Comment by theahura** [comment]
Fixed. I knew that this was an issue for a while and meant to fix it but I got caught up with personal life.
