### ISSUE TITLE
Delete messages between date ranges

### ISSUE THREAD

**Issue by tonywong332** [theahura/shoot-the-messenger#82]
I'm guessing the issue 46 caveat is fixed based off https://github.com/theahura/shoot-the-messenger/issues/46

Would like to be able to delete messages based off the date ranger. ie allow users to select messages older than timestamp N or newer than timestamp N or between timestamp N and N + delta t.

Also would be nice to have the ability to only unsend, only remove, or have a combination of unsend + remove, and also the ability to select whether to only remove self messages or messages from all conversation participants.

**Comment by theahura** [comment]
See #29 for the date range support. 

Re remove: this is a pretty single purpose tool and I don't have a lot of motivation for adding flexibility like what you are requesting. I can't think of when `remove` would be useful compared to unsend

Re: removing self messages or all messages, removing messages from the other person can be accomplished by just deleting the messenger thread after StM is completed, and I think that's easier than trying to shoe horn that behavior into the existing tool
