### ISSUE TITLE
It's removing only from my side

### ISSUE THREAD

**Issue by MuttakinHasib** [theahura/shoot-the-messenger#88]
How can I remove messages from both sides?

@theahura can you please help me?

**Comment by 8SecSleeper** [comment]
Your asking for something that is outside the scope of this tool. It's meant to unsend only your side. When it's done, you can simply delete the chat. If you don't care about removing the data from recipient's side of conversation and you merely want to delete the chat, Then you don't need to use this tool. Just select the Facebook option to delete chat.

**Comment by MuttakinHasib** [comment]
Old conversation and there is no option to delete the conversation

**Comment by theahura** [comment]
If there's no option to delete the conversation, unfortunately there's nothing we can do either. This tool doesn't have privileged access to Facebook, it's just making the task of pressing some buttons a bit less tedious by doing it automatically. Wish we could help but I don't think there's anything we can do here
