### ISSUE TITLE
Getting an ERROR

### ISSUE THREAD

**Issue by corrinefergg** [theahura/shoot-the-messenger#91]
Getting an “ERROR: something went wrong. Failed to complete removal” notification everytime I use it for roughly 10-20 seconds.

**Comment by aa3281** [comment]
same

**Comment by theahura** [comment]
I can't replicate this on my end :thinking: what version of the tool are you on? what version of chrome? can you share a dump of the logs?

**Comment by corrinefergg** [comment]
> I can't replicate this on my end 🤔 what version of the tool are you on? what version of chrome? can you share a dump of the logs?

I was on the newest version and i dont have a log anymore unfortunately as ive removed all i needed to :( sorry!! All i did was stay on top of it and keep refreshing everytime it happened
