### ISSUE TITLE
Plugin don't work

### ISSUE THREAD

**Issue by jbartak** [theahura/shoot-the-messenger#95]
**Describe the bug**
Freshly installed plugin from Chrome App store don't work. It just wont remove any messages.

**To Reproduce**
1. Click remove messages and nothing happens.

**Expected behavior**
Plugin should work.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser: Chrome
 - Version: 112.0.5615.165  64bit

**Logs**
![image](https://github.com/theahura/shoot-the-messenger/assets/9643757/d84a9027-2f03-4615-b7f9-c581c14ece5d)

**Comment by theahura** [comment]
Thanks for the bug report. Just pushed a change that should fix it. TLDR: looks like facebook changed the ordering of some of their ui elements, which was resulting in the scroller being in a totally different place

**Comment by jbartak** [comment]
Great, thx.
