### ISSUE TITLE
Currently not working

### ISSUE THREAD

**Issue by cassandrakeen** [theahura/shoot-the-messenger#96]
**Describe the bug**

**To Reproduce**
1. Go to 'messenger.com'
2. Click on '.shoot the messenger'
3. Scroll down to '.remove messages'
4. Nothing happens

**Expected behavior**
It will scroll to the top and remove messages

**Screenshots**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Chromebook
 - Browser Chrome
 - Version 

**Logs**
main.js:464 Got action:  REMOVE
main.js:281 Starting runner removal for N iterations:  10
main.js:283 Running count: 0
main.js:124 Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'Document': '.x78zum5.xdt5ytf.x193iq5w.x1n2onr6.xuk3077:has(> span)' is not a valid selector.
    at prepareDOMForRemoval (chrome-extension://lkhmjelfhkidbekjkghmbacoaolbcmep/main.js:124:41)
    at unsendAllVisibleMessages (chrome-extension://lkhmjelfhkidbekjkghmbacoaolbcmep/main.js:161:36)
    at runner (chrome-extension://lkhmjelfhkidbekjkghmbacoaolbcmep/main.js:284:29)
    at removeHandler (chrome-extension://lkhmjelfhkidbekjkghmbacoaolbcmep/main.js:392:24)
main.js:464 Got action:  REMOVE
main.js:281 Starting runner removal for N iterations:  10
main.js:283 Running count: 0
main.js:124 Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'Document': '.x78zum5.xdt5ytf.x193iq5w.x1n2onr6.xuk3077:has(> span)' is not a valid selector.
    at prepareDOMForRemoval (chrome-extension://lkhmjelfhkidbekjkghmbacoaolbcmep/main.js:124:41)
    at unsendAllVisibleMessages (chrome-extension://lkhmjelfhkidbekjkghmbacoaolbcmep/main.js:161:36)
    at runner (chrome-extension://lkhmjelfhkidbekjkghmbacoaolbcmep/main.js:284:29)
    at removeHandler (chrome-extension://lkhmjelfhkidbekjkghmbacoaolbcmep/main.js:392:24)
main.js:464 Got action:  UPDATE_DELAY
main.js:476 Setting delay to 5 seconds
main.js:464 Got action:  UPDATE_DELAY
main.js:476 Setting delay to  seconds
main.js:464 Got action:  UPDATE_DELAY
main.js:476 Setting delay to 2 seconds
main.js:464 Got action:  REMOVE
main.js:281 Starting runner removal for N iterations:  10
main.js:283 Running count: 0
main.js:124 Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'Document': '.x78zum5.xdt5ytf.x193iq5w.x1n2onr6.xuk3077:has(> span)' is not a valid selector.
    at prepareDOMForRemoval (chrome-extension://lkhmjelfhkidbekjkghmbacoaolbcmep/main.js:124:41)
    at unsendAllVisibleMessages (chrome-extension://lkhmjelfhkidbekjkghmbacoaolbcmep/main.js:161:36)
    at runner (chrome-extension://lkhmjelfhkidbekjkghmbacoaolbcmep/main.js:284:29)
    at removeHandler (chrome-extension://lkhmjelfhkidbekjkghmbacoaolbcmep/main.js:392:24)
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by theahura** [comment]
> DOMException: Failed to execute 'querySelectorAll' on 'Document': '.x78zum5.xdt5ytf.x193iq5w.x1n2onr6.xuk3077:has(> span)' is not a valid selector.

Interesting. What version of chrome are you on? I was able to test this successfully on `Version 113.0.5672.63 (Official Build) (64-bit)`. You can check by going to settings > about chrome

**Comment by theahura** [comment]
out of curiosity, do you have only unsent messages currently on screen? It looks like there is a bug where, if the only messages that are on screen are messages that have already been unsent, the extension cannot find the scroll bar

**Comment by cassandrakeen** [comment]
yes i do!  is there anyway i can make it work? should i scroll up manually

**Comment by theahura** [comment]
scrolling up manually until you have at least one message on screen (either yours or someone elses) is a quick fix. You could also (depending on the circumstance) just post another message to the thread

Whats happening behind the scenes:
- the tool uses the html elements for the existing messages to find the scrollbar
- for some reason, the 'unsent message' message does not match the query we use to find existing messages
- if only 'unsent message' messages are loaded in, the query for existing messages fails
- this results in the extension not being able to find the scrollbar, which causes immediate failure

should be a pretty straightforward fix. I'll see if I can get a fix out this weekend

**Comment by cassandrakeen** [comment]
tried scrolling up manually but it's not working :( hopefully there will be a way around this.  appreciate your responses!

**Comment by Nomeeci** [comment]
It's not working for me either, also when I click the dots to "unsend for everyone " it says "remove for you"

**Comment by cassandrakeen** [comment]
could you possibly update this thread once you get a fix? thanks so much!

**Comment by theahura** [comment]
should be fixed, need to deploy a live version
